package awr.witcher;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.os.*;
import android.text.*;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import org.json.*;
import java.util.*;
import java.util.regex.*;

/** HiTV section rendered with the host Anime Witcher visual language. */
final class HitvExperience {
    private HitvExperience(){}
    static void open(Context context){Context x=context;while(x instanceof ContextWrapper&&!(x instanceof Activity))x=((ContextWrapper)x).getBaseContext();if(!(x instanceof Activity)){Toast.makeText(context,"تعذر فتح HiTV من هذه الشاشة.",Toast.LENGTH_SHORT).show();return;}new Screen((Activity)x).show();}

    static final class Item {String id="",name="بدون عنوان",vertical="",horizontal="",intro="",update="",area="",genre="";int category=1,episodes=1;boolean categoryKnown;final ArrayList<Integer> episodeNumbers=new ArrayList<>();double score;}
    static final class Source {final ArrayList<HitvPlayback.Caption> captions=new ArrayList<>();final Map<String,String> headers=new TreeMap<>(String.CASE_INSENSITIVE_ORDER);String url,label,type;Source(String u,String l,String t){url=u;label=l;type=t;}}
    static final class State {String kind="home",title="HiTV",query="";Item item;ArrayList<Item> collection;State(String k){kind=k;}}
    static final class Section {String title;ArrayList<Item> items=new ArrayList<>();Section(String t){title=t;}}

    static final class Screen {
        final Activity a;final Handler handler=new Handler(Looper.getMainLooper());final ArrayDeque<State> back=new ArrayDeque<>();
        Dialog dialog;LinearLayout root,content;ScrollView scroll;State state=new State("home");int generation,homeType;Runnable searchTask;
        Screen(Activity activity){a=activity;}
        int bg(){return Ui.bg(a);}int surface(){return Ui.surface(a);}int textColor(){return Ui.textColor(a);}int muted(){return Ui.muted(a);}int accent(){return Ui.ACCENT;}

        void show(){
            dialog=new Dialog(a,android.R.style.Theme_Black_NoTitleBar_Fullscreen);dialog.setOnDismissListener(d->{generation++;handler.removeCallbacksAndMessages(null);});dialog.setOnKeyListener((d,key,event)->{if(key!=KeyEvent.KEYCODE_BACK)return false;if(event.getAction()==KeyEvent.ACTION_UP)goBack();return true;});render();dialog.show();Window w=dialog.getWindow();if(w!=null){w.setLayout(-1,-1);w.setBackgroundDrawable(new ColorDrawable(bg()));w.setStatusBarColor(bg());w.setNavigationBarColor(bg());}}
        void render(){
            generation++;if(searchTask!=null)handler.removeCallbacks(searchTask);root=Ui.column(a);root.setBackgroundColor(bg());root.addView(topBar(),new LinearLayout.LayoutParams(-1,Ui.dp(a,64)));
            scroll=new ScrollView(a);scroll.setFillViewport(true);scroll.setBackgroundColor(bg());content=Ui.column(a);content.setPadding(Ui.dp(a,12),Ui.dp(a,2),Ui.dp(a,12),Ui.dp(a,28));scroll.addView(content,new ScrollView.LayoutParams(-1,-2));root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));WitcherTabs tabs=new WitcherTabs(a);tabs.bind(4,tab->{dialog.dismiss();if(tab==0){if(a instanceof DramaActivity)a.finish();}else a.startActivity(new Intent(a,DramaActivity.class).putExtra("tab",tab));});root.addView(tabs,new LinearLayout.LayoutParams(-1,Ui.dp(a,64)));if(dialog!=null)dialog.setContentView(root);
            if("search".equals(state.kind))renderSearch();else if("detail".equals(state.kind))renderDetail();else if("collection".equals(state.kind))addGrid(content,state.collection);else renderHome();
        }
        View topBar(){
            LinearLayout bar=Ui.row(a);bar.setPadding(Ui.dp(a,8),Ui.dp(a,6),Ui.dp(a,8),Ui.dp(a,6));bar.setBackgroundColor(surface());
            View backView;if(back.isEmpty()){TextView close=Ui.text(a,"✕",24,true);close.setGravity(Gravity.CENTER);Ui.clickable(close,surface(),18);close.setOnClickListener(v->dialog.dismiss());backView=close;}else{Ui.Icon arrow=new Ui.Icon(a,"back",textColor());arrow.setPadding(Ui.dp(a,13),Ui.dp(a,13),Ui.dp(a,13),Ui.dp(a,13));Ui.clickable(arrow,surface(),18);arrow.setOnClickListener(v->goBack());backView=arrow;}bar.addView(backView,new LinearLayout.LayoutParams(Ui.dp(a,48),Ui.dp(a,48)));
            LinearLayout titles=Ui.column(a);TextView title=Ui.text(a,state.title==null?"HiTV":state.title,20,true);title.setMaxLines(1);title.setEllipsize(TextUtils.TruncateAt.END);titles.addView(title);TextView sub=Ui.text(a,"أفلام • مسلسلات",11,false);sub.setTextColor(muted());titles.addView(sub);bar.addView(titles,new LinearLayout.LayoutParams(0,-2,1));
            Ui.Icon search=new Ui.Icon(a,"search",accent());search.setPadding(Ui.dp(a,12),Ui.dp(a,12),Ui.dp(a,12),Ui.dp(a,12));search.setContentDescription("بحث HiTV");Ui.clickable(search,surface(),18);search.setOnClickListener(v->{if(!"search".equals(state.kind)){State n=new State("search");n.title="بحث HiTV";navigate(n);}});bar.addView(search,new LinearLayout.LayoutParams(Ui.dp(a,48),Ui.dp(a,48)));return bar;
        }
        void goBack(){if(back.isEmpty()){dialog.dismiss();return;}state=back.removeLast();render();}
        void navigate(State next){back.addLast(state);state=next;render();}
        TextView text(String s,int size,boolean bold){return Ui.text(a,s,size,bold);}
        TextView button(String s){return Ui.button(a,s,v->{});}
        void loading(){ProgressBar p=new ProgressBar(a);p.setIndeterminateTintList(android.content.res.ColorStateList.valueOf(accent()));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(Ui.dp(a,38),Ui.dp(a,38));lp.gravity=Gravity.CENTER;lp.topMargin=lp.bottomMargin=Ui.dp(a,42);content.addView(p,lp);}
        void message(String s){TextView t=text(s,15,false);t.setTextColor(muted());t.setGravity(Gravity.CENTER);t.setPadding(Ui.dp(a,18),Ui.dp(a,30),Ui.dp(a,18),Ui.dp(a,24));content.addView(t,new LinearLayout.LayoutParams(-1,-2));}
        void heading(String s){TextView h=text(s,19,true);h.setPadding(Ui.dp(a,2),Ui.dp(a,18),Ui.dp(a,2),Ui.dp(a,8));content.addView(h);}

        void renderHome(){
            LinearLayout intro=Ui.row(a);intro.setPadding(Ui.dp(a,4),Ui.dp(a,8),Ui.dp(a,4),Ui.dp(a,8));TextView brand=text("HiTV",28,true);brand.setTextColor(accent());intro.addView(brand);TextView source=text("  أفلام ومسلسلات من المصدر الأصلي",13,false);source.setTextColor(muted());intro.addView(source,new LinearLayout.LayoutParams(0,-2,1));content.addView(intro);
            LinearLayout chips=Ui.row(a);String[] names={"الكل","غربي","كوري"};for(int i=0;i<3;i++){final int n=i;TextView b=button(names[i]);boolean active=i==homeType;b.setTextColor(active?Color.BLACK:textColor());Ui.clickable(b,active?accent():surface(),14);b.setOnClickListener(v->{homeType=n;render();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,Ui.dp(a,46),1);lp.setMargins(Ui.dp(a,4),0,Ui.dp(a,4),0);chips.addView(b,lp);}content.addView(chips);
            loading();new HomeCollector(generation).start();
        }
        final class HomeCollector {
            final int token;int pending=8,success;final TreeMap<Integer,ArrayList<Section>> slots=new TreeMap<>();HomeCollector(int t){token=t;}
            void start(){
                request(0,"مختارات HiTV","/cms/web/hitv/homePage/firstPage",new JSONObject(),false,true);
                request(1,"مختارات HiTV","/cms/web/hitv/homePage/album/page",HitvApi.params("sequence",0,"type",homeType),false,true);
                request(2,"أفلام HiTV","/cms/web/hitv/movieDrama/moviePage",new JSONObject(),false,false);
                request(3,"مسلسلات HiTV","/cms/web/hitv/movieDrama/dramaPage",new JSONObject(),false,false);
                request(4,"الأكثر مشاهدة","/cms/web/hitv/search/leaderboard",new JSONObject(),false,false);
                request(5,"مختارات اليوم","/cms/web/pc/homePage/singleAlbums",HitvApi.params("type",homeType),false,true);
                request(6,"مقترحات HiTV","/cms/web/pc/homePage/banners",HitvApi.params("type",homeType),false,false);
                request(7,"الأكثر رواجاً","/cms/web/pc/search/searchLeaderboard",HitvApi.params("type",homeType),false,false);
            }
            void request(int order,String title,String path,JSONObject params,boolean post,boolean keepSections){HitvApi.Callback cb=(value,error)->{if(token!=generation||!"home".equals(state.kind))return;ArrayList<Section> out=new ArrayList<>();if(error==null&&value!=null&&value!=JSONObject.NULL){if(keepSections)out.addAll(sections(value));ArrayList<Item> raw=items(value);if((out.isEmpty()||!keepSections)&&!raw.isEmpty()){Section s=new Section(title);s.items.addAll(raw);out.add(s);}if(!out.isEmpty())success++;}slots.put(order,out);if(--pending==0)finish();};if(post)HitvApi.post(path,params,cb);else HitvApi.get(path,params,cb);}
            void finish(){if(token!=generation)return;while(content.getChildCount()>2)content.removeViewAt(2);LinkedHashMap<String,Section> merged=new LinkedHashMap<>();for(ArrayList<Section> group:slots.values())for(Section s:group){if(s==null||s.items.isEmpty())continue;String key=s.title==null||s.title.trim().isEmpty()?"HiTV":s.title.trim();Section existing=merged.get(key);if(existing==null){existing=new Section(key);merged.put(key,existing);}appendUnique(existing.items,s.items,30);}
                if(merged.isEmpty()){message("تعذر تحميل محتوى HiTV من هذه الشبكة. اضغط إعادة المحاولة بعد لحظات.");TextView retry=button("إعادة المحاولة");retry.setOnClickListener(v->render());content.addView(retry);return;}
                Item hero=null;for(Section s:merged.values())if(!s.items.isEmpty()){hero=s.items.get(0);break;}if(hero!=null)addHero(hero);for(Section s:merged.values())addRail(s.title,s.items);
            }
        }
        void addHero(Item item){
            FrameLayout box=new FrameLayout(a);box.setBackground(Ui.rounded(a,surface(),14));box.setClipToOutline(true);ImageView image=Ui.image(a,item.horizontal.isEmpty()?item.vertical:item.horizontal,14);box.addView(image,new FrameLayout.LayoutParams(-1,-1));GradientDrawable shade=new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{0x00000000,0x22000000,0xdd000000});View overlay=new View(a);overlay.setBackground(shade);box.addView(overlay,new FrameLayout.LayoutParams(-1,-1));
            LinearLayout labels=Ui.column(a);labels.setGravity(Gravity.BOTTOM);labels.setPadding(Ui.dp(a,16),Ui.dp(a,12),Ui.dp(a,16),Ui.dp(a,14));TextView badge=text(item.category==0?"فيلم • HiTV":"مسلسل • HiTV",12,true);badge.setTextColor(Color.BLACK);badge.setGravity(Gravity.CENTER);Ui.clickable(badge,accent(),10);LinearLayout.LayoutParams bp=new LinearLayout.LayoutParams(-2,Ui.dp(a,30));labels.addView(badge,bp);TextView title=text(item.name,23,true);title.setTextColor(Color.WHITE);title.setMaxLines(2);LinearLayout.LayoutParams tp=new LinearLayout.LayoutParams(-1,-2);tp.topMargin=Ui.dp(a,7);labels.addView(title,tp);if(!item.update.isEmpty()){TextView u=text(item.update,12,false);u.setTextColor(0xffdddddd);labels.addView(u);}box.addView(labels,new FrameLayout.LayoutParams(-1,-1));box.setOnClickListener(v->openDetail(item));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,Ui.dp(a,220));lp.topMargin=Ui.dp(a,12);content.addView(box,lp);
        }
        void addRail(String title,ArrayList<Item> list){if(list==null||list.isEmpty())return;LinearLayout head=Ui.row(a);TextView label=text(title,19,true);head.addView(label,new LinearLayout.LayoutParams(0,Ui.dp(a,56),1));TextView all=button("عرض الكل");all.setTextColor(accent());all.setOnClickListener(v->{State n=new State("collection");n.title=title;n.collection=list;navigate(n);});head.addView(all,new LinearLayout.LayoutParams(-2,Ui.dp(a,44)));content.addView(head);HorizontalScrollView sc=new HorizontalScrollView(a);sc.setHorizontalScrollBarEnabled(false);LinearLayout rail=new LinearLayout(a);rail.setOrientation(LinearLayout.HORIZONTAL);rail.setLayoutDirection(View.LAYOUT_DIRECTION_LTR);for(int i=0;i<list.size()&&i<24;i++){Item item=list.get(i);LinearLayout card=card(item,Ui.dp(a,124),Ui.dp(a,174));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(Ui.dp(a,124),Ui.dp(a,244));cp.setMargins(Ui.dp(a,4),0,Ui.dp(a,4),0);rail.addView(card,cp);}sc.addView(rail,new HorizontalScrollView.LayoutParams(-2,-2));content.addView(sc,new LinearLayout.LayoutParams(-1,Ui.dp(a,250)));}
        LinearLayout card(Item item,int w,int imageH){LinearLayout card=Ui.column(a);Ui.clickable(card,surface(),12);ImageView image=Ui.image(a,item.vertical.isEmpty()?item.horizontal:item.vertical,12);card.addView(image,new LinearLayout.LayoutParams(-1,imageH));TextView name=text(item.name,13,true);name.setMaxLines(2);name.setEllipsize(TextUtils.TruncateAt.END);name.setPadding(Ui.dp(a,7),Ui.dp(a,5),Ui.dp(a,7),0);card.addView(name,new LinearLayout.LayoutParams(-1,Ui.dp(a,42)));if(item.score>0){TextView score=text(String.format(Locale.ROOT,"★ %.1f",item.score),11,true);score.setTextColor(accent());score.setPadding(Ui.dp(a,7),0,Ui.dp(a,7),Ui.dp(a,5));card.addView(score);}card.setOnClickListener(v->openDetail(item));return card;}
        void openDetail(Item item){State n=new State("detail");n.item=item;n.title=item.name;navigate(n);}

        void renderSearch(){
            EditText field=new EditText(a);field.setSingleLine(true);field.setHint("ابحث في HiTV…");field.setHintTextColor(muted());field.setTextColor(textColor());field.setTextSize(16);field.setPadding(Ui.dp(a,16),0,Ui.dp(a,16),0);field.setBackground(Ui.rounded(a,surface(),12));field.setImeOptions(android.view.inputmethod.EditorInfo.IME_ACTION_SEARCH);field.setText(state.query);content.addView(field,new LinearLayout.LayoutParams(-1,Ui.dp(a,52)));LinearLayout results=Ui.column(a);content.addView(results);
            if(state.query.trim().isEmpty())showTrending(results);else search(state.query,results,++generation);
            field.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int st,int c,int after){}public void afterTextChanged(Editable e){}public void onTextChanged(CharSequence s,int st,int before,int count){String q=s.toString().trim();state.query=q;if(searchTask!=null)handler.removeCallbacks(searchTask);results.removeAllViews();int token=++generation;if(q.isEmpty()){showTrending(results);return;}searchTask=()->search(q,results,token);handler.postDelayed(searchTask,400);}});
            field.setOnEditorActionListener((v,action,event)->{String q=field.getText().toString().trim();state.query=q;if(searchTask!=null)handler.removeCallbacks(searchTask);results.removeAllViews();int token=++generation;if(!q.isEmpty())search(q,results,token);else showTrending(results);((InputMethodManager)a.getSystemService(Context.INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(field.getWindowToken(),0);return true;});
        }
        void showTrending(LinearLayout target){final int token=generation;TextView h=text("الأكثر بحثاً على HiTV",18,true);h.setPadding(0,Ui.dp(a,18),0,Ui.dp(a,10));target.addView(h);HitvApi.get("/cms/web/hitv/search/leaderboard",new JSONObject(),(value,error)->{if(error!=null||token!=generation||!"search".equals(state.kind))return;ArrayList<Item> list=items(value);if(!list.isEmpty())addGrid(target,list);});}
        void search(String query,LinearLayout results,int token){
            ProgressBar p=new ProgressBar(a);p.setIndeterminateTintList(android.content.res.ColorStateList.valueOf(accent()));LinearLayout.LayoutParams pl=new LinearLayout.LayoutParams(Ui.dp(a,34),Ui.dp(a,34));pl.gravity=Gravity.CENTER;pl.topMargin=Ui.dp(a,24);results.addView(p,pl);new SearchCollector(query,results,token).start();
        }
        final class SearchCollector {
            final String query;final LinearLayout target;final int token;int pending=3;final ArrayList<Item> all=new ArrayList<>();int failures;
            SearchCollector(String q,LinearLayout t,int k){query=q;target=t;token=k;}
            void start(){request("/cms/web/hitv/movieDrama/searchWithKeyWord",HitvApi.params("size",50,"searchKeyWord",query),true);request("/cms/web/hitv/search/search",HitvApi.params("page",0,"size",50,"searchKeyWord",query),true);request("/cms/web/pc/search/searchLenovo",HitvApi.params("size",20,"searchKeyWord",query),true);}
            void request(String path,JSONObject params,boolean post){HitvApi.Callback cb=(value,error)->{if(token!=generation||!"search".equals(state.kind))return;if(error!=null)failures++;else appendUnique(all,items(value),80);if(--pending==0)finish();};if(post)HitvApi.post(path,params,cb);else HitvApi.get(path,params,cb);}
            void finish(){if(token!=generation)return;target.removeAllViews();if(all.isEmpty()){TextView m=text(failures==3?"تعذر البحث في HiTV حالياً. حاول مرة أخرى.":"لم نجد نتائج لهذا الاسم في HiTV.",15,false);m.setTextColor(muted());m.setGravity(Gravity.CENTER);m.setPadding(0,Ui.dp(a,34),0,0);target.addView(m);return;}TextView h=text("نتائج HiTV  •  "+all.size(),18,true);h.setPadding(0,Ui.dp(a,16),0,Ui.dp(a,10));target.addView(h);addGrid(target,all);}
        }
        void addGrid(LinearLayout parent,ArrayList<Item> list){int gap=Ui.dp(a,7);LinearLayout row=null;for(int i=0;i<list.size();i++){if(i%3==0){row=new LinearLayout(a);row.setOrientation(LinearLayout.HORIZONTAL);row.setLayoutDirection(View.LAYOUT_DIRECTION_LTR);parent.addView(row,new LinearLayout.LayoutParams(-1,Ui.dp(a,232)));}LinearLayout card=card(list.get(i),0,Ui.dp(a,154));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,Ui.dp(a,226),1);lp.setMargins(gap/2,0,gap/2,Ui.dp(a,6));row.addView(card,lp);}if(row!=null)for(int i=list.size()%3;i>0&&i<3;i++)row.addView(new View(a),new LinearLayout.LayoutParams(0,1,1));}

        void renderDetail(){Item initial=state.item;if(initial==null){message("تعذر فتح هذا العمل.");return;}final int token=generation;loading();HitvApi.get("/cms/web/hitv/movieDrama/detail",HitvApi.params("id",initial.id,"category",initial.category),(value,error)->{if(token!=generation||!"detail".equals(state.kind))return;content.removeAllViews();Item item=initial;if(error==null){ArrayList<Item> found=items(value);if(!found.isEmpty())item=merge(initial,found.get(0));else if(value instanceof JSONObject)item=merge(initial,normalize((JSONObject)value));}state.item=item;drawDetail(item);});}
        void drawDetail(Item item){
            ImageView cover=Ui.image(a,item.horizontal.isEmpty()?item.vertical:item.horizontal,14);content.addView(cover,new LinearLayout.LayoutParams(-1,Ui.dp(a,225)));TextView name=text(item.name,24,true);name.setPadding(Ui.dp(a,2),Ui.dp(a,14),Ui.dp(a,2),Ui.dp(a,5));content.addView(name);ArrayList<String> meta=new ArrayList<>();if(item.score>0)meta.add(String.format(Locale.ROOT,"★ %.1f",item.score));if(!item.area.isEmpty())meta.add(item.area);if(!item.genre.isEmpty())meta.add(item.genre);if(!item.update.isEmpty())meta.add(item.update);if(!meta.isEmpty()){TextView m=text(TextUtils.join("  •  ",meta),13,false);m.setTextColor(muted());content.addView(m);}if(!item.intro.isEmpty()){TextView intro=text(item.intro,15,false);intro.setTextColor(textColor());intro.setLineSpacing(Ui.dp(a,4),1f);intro.setPadding(Ui.dp(a,2),Ui.dp(a,13),Ui.dp(a,2),Ui.dp(a,6));content.addView(intro);}
            TextView play=button(item.category==1&&item.episodes>1?"اختر الحلقة للمشاهدة":"▶  مشاهدة الآن");play.setTextColor(Color.BLACK);Ui.clickable(play,accent(),12);play.setOnClickListener(v->{if(item.category==1&&item.episodes>1)showEpisodes();else play(item,1);});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,Ui.dp(a,52));lp.topMargin=Ui.dp(a,16);content.addView(play,lp);
            if(item.category==0){TextView download=button("تنزيل من HiTV");download.setOnClickListener(v->download(item,1));LinearLayout.LayoutParams dp=new LinearLayout.LayoutParams(-1,Ui.dp(a,50));dp.topMargin=Ui.dp(a,8);content.addView(download,dp);}if(item.category==1&&item.episodes>1)showEpisodeButtons(item,Math.min(item.episodes,300));
        }
        void showEpisodes(){scroll.post(()->scroll.smoothScrollTo(0,Math.max(0,content.getHeight()-a.getResources().getDisplayMetrics().heightPixels/2)));}
        void showEpisodeButtons(Item item,int count){TextView head=text("الحلقات  •  "+count,19,true);head.setPadding(0,Ui.dp(a,22),0,Ui.dp(a,9));content.addView(head);GridLayout grid=new GridLayout(a);grid.setColumnCount(5);grid.setAlignmentMode(GridLayout.ALIGN_BOUNDS);grid.setUseDefaultMargins(false);int gap=Ui.dp(a,3);for(int i=1;i<=count;i++){final int ep=item.episodeNumbers.isEmpty()?i:item.episodeNumbers.get(i-1);TextView b=button(Integer.toString(ep));b.setOnClickListener(v->play(item,ep));b.setOnLongClickListener(v->{download(item,ep);return true;});GridLayout.LayoutParams gp=new GridLayout.LayoutParams();gp.width=0;gp.height=Ui.dp(a,46);gp.columnSpec=GridLayout.spec(GridLayout.UNDEFINED,1,1f);gp.setMargins(gap,gap,gap,gap);grid.addView(b,gp);}content.addView(grid,new LinearLayout.LayoutParams(-1,-2));TextView hint=text("اضغط مطولاً على رقم الحلقة للتنزيل",12,false);hint.setTextColor(muted());hint.setPadding(0,Ui.dp(a,8),0,0);content.addView(hint);}
        void play(Item item,int episode){final int token=generation;ProgressDialog wait=new ProgressDialog(a);wait.setMessage("جاري تجهيز تشغيل HiTV…");wait.setCancelable(true);final boolean[] canceled={false};wait.setOnCancelListener(d->canceled[0]=true);wait.show();HitvApi.get("/cms/web/hitv/movieDrama/getPlayInfo",HitvApi.params("id",item.id,"category",item.category,"seriesNo",episode),(value,error)->{if(wait.isShowing())wait.dismiss();if(canceled[0]||token!=generation||dialog==null||!dialog.isShowing())return;if(error!=null){alert(error);return;}ArrayList<Source> list=sources(value);if(list.isEmpty()){alert("لا يوجد رابط تشغيل متاح لهذه الحلقة حالياً.");return;}chooseSource(item.name+(item.category==1?" • الحلقة "+episode:""),list,false);});}
        void download(Item item,int episode){final int token=generation;ProgressDialog wait=new ProgressDialog(a);wait.setMessage("جاري تجهيز تنزيل HiTV…");wait.setCancelable(true);final boolean[] canceled={false};wait.setOnCancelListener(d->canceled[0]=true);wait.show();HitvApi.get("/cms/web/hitv/movieDrama/getPlayInfo",HitvApi.params("id",item.id,"category",item.category,"seriesNo",episode),(value,error)->{if(wait.isShowing())wait.dismiss();if(canceled[0]||token!=generation||dialog==null||!dialog.isShowing())return;if(error!=null){alert(error);return;}ArrayList<Source> list=sources(value);if(list.isEmpty()){alert("لا توجد جودة تنزيل متاحة لهذا العمل حالياً.");return;}chooseSource(item.name+(item.category==1?" • الحلقة "+episode:""),list,true);});}
        void chooseSource(String title,ArrayList<Source> list,boolean download){if(list.size()==1){openSource(title,list.get(0),download);return;}String[] labels=new String[list.size()];for(int i=0;i<list.size();i++)labels[i]=(list.get(i).label==null||list.get(i).label.trim().isEmpty()?"جودة "+(i+1):list.get(i).label);new AlertDialog.Builder(a).setTitle(download?"اختر جودة التنزيل":"اختر جودة التشغيل").setItems(labels,(d,i)->openSource(title,list.get(i),download)).show();}
        void openSource(String title,Source s,boolean download){if(!download){HitvPlayer.play(a,title,s);return;}String mime=HitvPlayer.mime(s.type,s.url);DownloadFlow.open(a,s.url,s.headers,title,"application/x-mpegURL".equals(mime)||"application/dash+xml".equals(mime));}
        void alert(String s){if(!a.isFinishing()&&!a.isDestroyed())new AlertDialog.Builder(a).setMessage(s).setPositiveButton("حسناً",null).show();}
    }

    static void appendUnique(ArrayList<Item> target,ArrayList<Item> incoming,int limit){HashSet<String> seen=new HashSet<>();for(Item i:target)seen.add(i.category+":"+i.id);for(Item i:incoming){String k=i.category+":"+i.id;if(i.id.isEmpty()||seen.contains(k))continue;target.add(i);seen.add(k);if(target.size()>=limit)break;}}
    static Item merge(Item a,Item b){if(b==null)return a;Item r=new Item();r.id=pick(b.id,a.id);r.name=pick(b.name,a.name);r.vertical=pick(b.vertical,a.vertical);r.horizontal=pick(b.horizontal,a.horizontal);r.intro=pick(b.intro,a.intro);r.update=pick(b.update,a.update);r.area=pick(b.area,a.area);r.genre=pick(b.genre,a.genre);r.category=b.categoryKnown?b.category:a.category;r.categoryKnown=a.categoryKnown||b.categoryKnown;r.episodeNumbers.addAll(b.episodeNumbers.isEmpty()?a.episodeNumbers:b.episodeNumbers);r.episodes=r.episodeNumbers.isEmpty()?Math.max(a.episodes,b.episodes):r.episodeNumbers.size();r.score=b.score>0?b.score:a.score;return r;}
    static String pick(String a,String b){return a!=null&&!a.trim().isEmpty()&&!"بدون عنوان".equals(a)?a:b;}
    static String first(JSONObject o,String... keys){for(String k:keys){Object v=o.opt(k);if(v instanceof String&&!((String)v).trim().isEmpty())return ((String)v).trim();if(v instanceof Number)return String.valueOf(v);}return "";}
    static Item normalize(JSONObject o){Item x=new Item();x.id=first(o,"id","contentId","relatedId","relationId");String name=first(o,"name","title");if(!name.isEmpty())x.name=name;x.vertical=first(o,"coverVerticalUrl","imageUrl","cover","bannerUrl","posterUrl");x.horizontal=first(o,"coverHorizontalUrl","bannerUrl","cover","imageUrl","coverVerticalUrl");x.intro=first(o,"introduction","description","summary");x.update=first(o,"updateInfo","episodeInfo");x.score=parseDouble(first(o,"score","rating"));Object cat=o.opt("domainType");if(cat==null||cat==JSONObject.NULL)cat=o.opt("category");String c=String.valueOf(cat);x.categoryKnown=cat!=null&&cat!=JSONObject.NULL;x.category=("0".equals(c)||"movie".equalsIgnoreCase(c))?0:1;Object area=o.opt("area");if(area instanceof JSONObject)x.area=first((JSONObject)area,"name");else if(area instanceof String)x.area=(String)area;Object tag=o.opt("categoryTag");if(tag instanceof JSONObject)x.genre=first((JSONObject)tag,"name");else if(tag instanceof String)x.genre=(String)tag;JSONArray eps=o.optJSONArray("episodeVo");if(eps==null)eps=o.optJSONArray("episodeList");if(eps!=null&&eps.length()>0){for(int i=0;i<eps.length();i++){JSONObject e=eps.optJSONObject(i);int number=e==null?eps.optInt(i,i+1):e.optInt("seriesNo",e.optInt("episodeNo",i+1));if(number>0&&!x.episodeNumbers.contains(number))x.episodeNumbers.add(number);}x.episodes=Math.max(1,x.episodeNumbers.size());}else{x.episodes=Math.max(1,o.optInt("episodeCount",1));if(x.episodes==1){Matcher m=Pattern.compile("(\\d+)").matcher(x.update);if(m.find())try{x.episodes=Math.max(1,Integer.parseInt(m.group(1)));}catch(Exception ignored){}}}return x;}
    static double parseDouble(String s){try{return Double.parseDouble(s);}catch(Exception e){return 0;}}
    static ArrayList<Item> items(Object value){LinkedHashMap<String,Item> map=new LinkedHashMap<>();collectItems(value,0,map);return new ArrayList<>(map.values());}
    static void collectItems(Object value,int depth,LinkedHashMap<String,Item> out){if(value==null||value==JSONObject.NULL||depth>9||out.size()>500)return;if(value instanceof JSONArray){JSONArray a=(JSONArray)value;for(int i=0;i<a.length();i++)collectItems(a.opt(i),depth+1,out);return;}if(!(value instanceof JSONObject))return;JSONObject o=(JSONObject)value;Item item=normalize(o);if(!item.id.isEmpty()&&(!item.vertical.isEmpty()||!item.horizontal.isEmpty()||item.categoryKnown&&!item.name.equals("بدون عنوان")))out.put(item.category+":"+item.id,item);Iterator<String> keys=o.keys();while(keys.hasNext()){Object next=o.opt(keys.next());if(next instanceof JSONObject||next instanceof JSONArray)collectItems(next,depth+1,out);}}
    static ArrayList<Section> sections(Object value){ArrayList<Section> out=new ArrayList<>();collectSections(value,0,out,new HashSet<String>());return out;}
    static void collectSections(Object value,int depth,ArrayList<Section> out,HashSet<String> seen){if(value==null||value==JSONObject.NULL||depth>8||out.size()>40)return;if(value instanceof JSONArray){JSONArray a=(JSONArray)value;for(int i=0;i<a.length();i++)collectSections(a.opt(i),depth+1,out,seen);return;}if(!(value instanceof JSONObject))return;JSONObject o=(JSONObject)value;JSONArray list=o.optJSONArray("recommendContentVOList");if(list==null)list=o.optJSONArray("contentList");if(list==null)list=o.optJSONArray("items");String title=first(o,"homeSectionName","sectionName","name","title");if(list!=null&&list.length()>0){ArrayList<Item> its=items(list);if(!its.isEmpty()){String key=(title.isEmpty()?"HiTV":title)+":"+its.get(0).id;if(seen.add(key)){Section s=new Section(title.isEmpty()?"مختارات HiTV":title);s.items.addAll(its);out.add(s);}}}Iterator<String> keys=o.keys();while(keys.hasNext()){Object next=o.opt(keys.next());if(next instanceof JSONObject||next instanceof JSONArray)collectSections(next,depth+1,out,seen);}}
    static ArrayList<Source> sources(Object value){return HitvPlayback.sources(value);}
    static boolean mediaUrl(String url){return HitvPlayback.media(url);}
}
