package awr.witcher;

import android.app.*;
import android.content.*;
import android.graphics.Color;
import android.net.Uri;
import android.text.*;
import android.view.*;
import android.view.inputmethod.InputMethodManager;
import android.widget.*;
import org.json.*;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;

/** Oscar TV catalogue UI using Anime Witcher colors and the source app's catalogue/detail/link structure. */
final class OscarExperience {
    private OscarExperience(){}
    static void open(Context context){Context x=context;while(x instanceof ContextWrapper&&!(x instanceof Activity))x=((ContextWrapper)x).getBaseContext();if(!(x instanceof Activity)){Toast.makeText(context,"تعذر فتح Oscar TV",Toast.LENGTH_SHORT).show();return;}new Screen((Activity)x).show();}

    static final class Item {int id;String kind="series",title="بدون عنوان",poster="",banner="",sub="";JSONObject raw;}
    static final class Link {String url="",deep="",name="سيرفر",quality="",type="";}
    static final class Screen {
        final Activity a;Dialog dialog;LinearLayout root,content;ScrollView scroll;int generation;String section="home";ArrayDeque<Runnable> backs=new ArrayDeque<>();
        Screen(Activity x){a=x;}
        void show(){dialog=new Dialog(a,android.R.style.Theme_Black_NoTitleBar_Fullscreen);dialog.setOnDismissListener(d->generation++);renderShell();dialog.show();Window w=dialog.getWindow();if(w!=null){w.setLayout(-1,-1);w.setStatusBarColor(Color.BLACK);w.setNavigationBarColor(Color.BLACK);}loadHome();}
        void renderShell(){root=Ui.column(a);root.setBackgroundColor(Color.BLACK);root.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);root.addView(top(),new LinearLayout.LayoutParams(-1,Ui.dp(a,62)));scroll=new ScrollView(a);scroll.setFillViewport(true);content=Ui.column(a);content.setPadding(Ui.dp(a,10),0,Ui.dp(a,10),Ui.dp(a,24));scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));root.addView(nav(),new LinearLayout.LayoutParams(-1,Ui.dp(a,62)));dialog.setContentView(root);}
        View top(){LinearLayout r=Ui.row(a);r.setPadding(Ui.dp(a,8),0,Ui.dp(a,8),0);r.setBackgroundColor(0xff080808);TextView close=Ui.text(a,"×",34,false);close.setGravity(Gravity.CENTER);close.setOnClickListener(v->{if(!backs.isEmpty())backs.removeLast().run();else dialog.dismiss();});r.addView(close,new LinearLayout.LayoutParams(Ui.dp(a,48),-1));TextView t=Ui.text(a,"OSCAR TV",22,true);t.setTextColor(Ui.ACCENT);t.setGravity(Gravity.CENTER);r.addView(t,new LinearLayout.LayoutParams(0,-1,1));TextView s=Ui.text(a,"⌕",30,false);s.setGravity(Gravity.CENTER);s.setOnClickListener(v->searchDialog());r.addView(s,new LinearLayout.LayoutParams(Ui.dp(a,52),-1));return r;}
        View nav(){LinearLayout n=new LinearLayout(a);n.setOrientation(LinearLayout.HORIZONTAL);n.setGravity(Gravity.CENTER);n.setBackgroundColor(0xff101010);String[] names={"الرئيسية","مسلسلات","أفلام","أنمي","قنوات"};String[] kinds={"home","series","movie","anime","channel"};for(int i=0;i<names.length;i++){final String k=kinds[i];TextView b=Ui.text(a,names[i],11,true);b.setGravity(Gravity.CENTER);b.setTextColor(section.equals(k)?Ui.ACCENT:Ui.muted(a));b.setOnClickListener(v->{section=k;backs.clear();if(k.equals("home"))loadHome();else loadList(k,null);});n.addView(b,new LinearLayout.LayoutParams(0,-1,1));}return n;}
        void clear(){content.removeAllViews();}
        void loading(){clear();ProgressBar p=new ProgressBar(a);p.setIndeterminateTintList(android.content.res.ColorStateList.valueOf(Ui.ACCENT));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(Ui.dp(a,42),Ui.dp(a,42));lp.gravity=Gravity.CENTER;lp.topMargin=Ui.dp(a,60);content.addView(p,lp);}
        void error(String e,Runnable retry){clear();TextView m=Ui.text(a,e==null?"تعذر تحميل محتوى Oscar TV":e,15,false);m.setTextColor(Ui.muted(a));m.setGravity(Gravity.CENTER);m.setPadding(Ui.dp(a,12),Ui.dp(a,42),Ui.dp(a,12),Ui.dp(a,26));content.addView(m);content.addView(Ui.button(a,"إعادة المحاولة",v->retry.run()),new LinearLayout.LayoutParams(-1,Ui.dp(a,52)));}
        void title(String s){TextView h=Ui.text(a,s,20,true);h.setPadding(Ui.dp(a,4),Ui.dp(a,18),0,Ui.dp(a,10));content.addView(h);}

        void loadHome(){section="home";renderShell();loading();int token=++generation;OscarApi.get("api/v2/home.php",OscarApi.params("app_version",114),(v,e)->{if(token!=generation)return;if(e!=null){error(e,this::loadHome);return;}clear();ArrayList<Item> all=collect(v,null,220);if(all.isEmpty()){error("لم يصل محتوى من Oscar TV.",this::loadHome);return;}ArrayList<Item> series=filter(all,"series"),movies=filter(all,"movie"),anime=filter(all,"anime"),channels=filter(all,"channel"),episodes=filter(all,"episode");Item hero=!series.isEmpty()?series.get(0):all.get(0);hero(hero);if(!episodes.isEmpty())rail("أحدث الحلقات",episodes);if(!series.isEmpty())rail("مسلسلات Oscar TV",series);if(!movies.isEmpty())rail("أفلام Oscar TV",movies);if(!anime.isEmpty())rail("الأنمي",anime);if(!channels.isEmpty())rail("القنوات",channels);});}
        void loadList(String kind,String q){section=kind;renderShell();loading();String path;Map<String,String> p;if(kind.equals("movie")){path="api/movies/";p=OscarApi.params("page",1,"limit",60,"app_version",114);}else if(kind.equals("anime")){path="api/anime/";p=OscarApi.params("page",1,"limit",60,"search",q);}else if(kind.equals("channel")){path="api/channels/";p=OscarApi.params("page",1,"limit",60,"search",q);}else{path="api/series/";p=OscarApi.params("page",1,"limit",60,"search",q,"app_version",114);}if(q!=null&&!q.isEmpty())p.put("search",q);int token=++generation;OscarApi.get(path,p,(v,e)->{if(token!=generation)return;if(e!=null){error(e,()->loadList(kind,q));return;}clear();ArrayList<Item> list=collect(v,kind,180);if(list.isEmpty()){TextView m=Ui.text(a,"لا توجد نتائج",16,false);m.setGravity(Gravity.CENTER);m.setTextColor(Ui.muted(a));m.setPadding(0,Ui.dp(a,45),0,0);content.addView(m);return;}grid(list);});}
        void searchDialog(){final EditText input=new EditText(a);input.setSingleLine(true);input.setHint("ابحث في Oscar TV");input.setTextColor(Color.WHITE);input.setHintTextColor(0xffaaaaaa);input.setBackground(Ui.rounded(a,0xff222222,12));input.setPadding(Ui.dp(a,14),0,Ui.dp(a,14),0);new AlertDialog.Builder(a).setTitle("بحث Oscar TV").setView(input).setNegativeButton("إلغاء",null).setPositiveButton("بحث",(d,w)->searchAll(input.getText().toString().trim())).show();}
        void searchAll(String q){if(q.isEmpty())return;section="search";renderShell();loading();ArrayList<Item> merged=new ArrayList<>();AtomicInteger left=new AtomicInteger(4);int token=++generation;String[] kinds={"series","movie","anime","channel"};for(String k:kinds){String path=k.equals("movie")?"api/movies/":k.equals("anime")?"api/anime/":k.equals("channel")?"api/channels/":"api/series/";Map<String,String> p=OscarApi.params("page",1,"limit",35,"search",q,"app_version",114);OscarApi.get(path,p,(v,e)->{if(token!=generation)return;if(e==null)merged.addAll(collect(v,k,80));if(left.decrementAndGet()==0){clear();if(merged.isEmpty()){TextView m=Ui.text(a,"لا توجد نتائج للبحث",16,false);m.setGravity(Gravity.CENTER);content.addView(m);}else grid(unique(merged));}});}}
        void hero(Item i){FrameLayout f=new FrameLayout(a);ImageView img=Ui.image(a,OscarApi.absolute(i.banner.isEmpty()?i.poster:i.banner),18);f.addView(img,new FrameLayout.LayoutParams(-1,-1));LinearLayout sh=Ui.column(a);sh.setGravity(Gravity.BOTTOM);sh.setPadding(Ui.dp(a,16),0,Ui.dp(a,16),Ui.dp(a,15));sh.setBackgroundColor(0x55000000);TextView brand=Ui.text(a,"OSCAR TV",12,true);brand.setTextColor(Ui.ACCENT);sh.addView(brand);TextView name=Ui.text(a,i.title,24,true);name.setMaxLines(2);sh.addView(name);if(!i.sub.isEmpty()){TextView su=Ui.text(a,i.sub,13,false);su.setTextColor(0xffdddddd);sh.addView(su);}f.addView(sh,new FrameLayout.LayoutParams(-1,-1));f.setOnClickListener(v->detail(i));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,Ui.dp(a,225));lp.topMargin=Ui.dp(a,10);content.addView(f,lp);}
        void rail(String name,ArrayList<Item> list){title(name);HorizontalScrollView hs=new HorizontalScrollView(a);hs.setHorizontalScrollBarEnabled(false);LinearLayout row=new LinearLayout(a);row.setOrientation(LinearLayout.HORIZONTAL);row.setLayoutDirection(View.LAYOUT_DIRECTION_LTR);for(int x=0;x<Math.min(22,list.size());x++){Item i=list.get(x);LinearLayout c=card(i);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(Ui.dp(a,132),Ui.dp(a,238));lp.setMargins(Ui.dp(a,5),0,Ui.dp(a,5),0);row.addView(c,lp);}hs.addView(row);content.addView(hs,new LinearLayout.LayoutParams(-1,Ui.dp(a,242)));}
        LinearLayout card(Item i){LinearLayout c=Ui.column(a);c.setBackground(Ui.rounded(a,0xff111111,13));ImageView im=Ui.image(a,OscarApi.absolute(i.poster),13);c.addView(im,new LinearLayout.LayoutParams(-1,Ui.dp(a,184)));TextView n=Ui.text(a,i.title,13,true);n.setMaxLines(2);n.setEllipsize(TextUtils.TruncateAt.END);n.setPadding(Ui.dp(a,7),Ui.dp(a,5),Ui.dp(a,7),0);c.addView(n,new LinearLayout.LayoutParams(-1,0,1));c.setOnClickListener(v->detail(i));return c;}
        void grid(ArrayList<Item> list){int gap=Ui.dp(a,6);LinearLayout row=null;for(int x=0;x<Math.min(120,list.size());x++){if(x%3==0){row=new LinearLayout(a);row.setOrientation(LinearLayout.HORIZONTAL);row.setLayoutDirection(View.LAYOUT_DIRECTION_LTR);content.addView(row,new LinearLayout.LayoutParams(-1,Ui.dp(a,222)));}LinearLayout c=card(list.get(x));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,Ui.dp(a,216),1);lp.setMargins(gap,gap,gap,gap);row.addView(c,lp);}}

        void detail(Item i){backs.addLast(()->{backs.clear();if(section.equals("home"))loadHome();else if(section.equals("search"))searchAll("");else loadList(section,null);});loading();String path=i.kind.equals("movie")?"api/movies/show.php":i.kind.equals("anime")?"api/anime/show.php":i.kind.equals("channel")?"api/channels/show.php":i.kind.equals("episode")?"api/episodes/show.php":"api/series/show.php";int token=++generation;OscarApi.get(path,OscarApi.params("id",i.id),(v,e)->{if(token!=generation)return;if(e!=null){error(e,()->detail(i));return;}JSONObject d=findObject(v);if(d==null)d=i.raw;drawDetail(i,d);});}
        void drawDetail(Item base,JSONObject d){clear();String banner=pick(d,"banner","cover","backdrop",base.banner,base.poster),poster=pick(d,"poster","thumbnail",base.poster);ImageView h=Ui.image(a,OscarApi.absolute(!banner.isEmpty()?banner:poster),18);content.addView(h,new LinearLayout.LayoutParams(-1,Ui.dp(a,235)));String name=pick(d,"title_ar","name","title","title_en",base.title);TextView n=Ui.text(a,name,25,true);n.setPadding(0,Ui.dp(a,14),0,Ui.dp(a,5));content.addView(n);String meta=join(pick(d,"release_year","season_year","country_name","country"),pick(d,"rating","quality_source","content_type"));if(!meta.isEmpty()){TextView m=Ui.text(a,meta,13,false);m.setTextColor(Ui.muted(a));content.addView(m);}String story=pick(d,"story","description","overview");if(!story.isEmpty()){TextView s=Ui.text(a,story,15,false);s.setTextColor(0xffdddddd);s.setPadding(0,Ui.dp(a,12),0,Ui.dp(a,10));content.addView(s);}ArrayList<Link> watch=links(d.opt("watch_links")),down=links(d.opt("download_links")),streams=links(d.opt("streams"));if(base.kind.equals("movie")){if(!watch.isEmpty())linkButtons("سيرفرات المشاهدة",watch,name,false);if(!down.isEmpty())linkButtons("سيرفرات التنزيل",down,name,true);return;}if(base.kind.equals("channel")){if(streams.isEmpty())streams=linksDeep(d);linkButtons("سيرفرات القناة",streams,name,false);return;}if(base.kind.equals("episode")){episodeLinks(base.id,d,name,watch,down);return;}ArrayList<Item> seasons=itemsFromArray(d.optJSONArray("seasons"),"season");if(!seasons.isEmpty()){seasonButtons(base,seasons);}else fetchSeasons(base);}
        void fetchSeasons(Item series){OscarApi.get(series.kind.equals("anime")?"api/anime/show.php":"api/seasons/",series.kind.equals("anime")?OscarApi.params("id",series.id):OscarApi.params("series_id",series.id),(v,e)->{if(e!=null)return;ArrayList<Item> s=series.kind.equals("anime")?itemsFromArray(findArrayByKey(v,"seasons"),"season"):collect(v,"season",80);if(!s.isEmpty())seasonButtons(series,s);});}
        void seasonButtons(Item series,ArrayList<Item> seasons){title("المواسم");for(Item s:seasons){TextView b=Ui.button(a,s.title,v->episodes(series,s));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,Ui.dp(a,50));lp.bottomMargin=Ui.dp(a,6);content.addView(b,lp);}}
        void episodes(Item series,Item season){loading();String path=series.kind.equals("anime")?"api/anime/episodes/":"api/episodes/";OscarApi.get(path,OscarApi.params("season_id",season.id),(v,e)->{if(e!=null){error(e,()->episodes(series,season));return;}clear();title(series.title+" · "+season.title);ArrayList<Item> eps=collect(v,"episode",250);if(eps.isEmpty()){TextView m=Ui.text(a,"لا توجد حلقات",16,false);m.setGravity(Gravity.CENTER);content.addView(m);return;}for(Item ep:eps){LinearLayout r=Ui.row(a);r.setBackground(Ui.rounded(a,0xff111111,12));ImageView im=Ui.image(a,OscarApi.absolute(ep.poster),10);r.addView(im,new LinearLayout.LayoutParams(Ui.dp(a,115),Ui.dp(a,78)));TextView t=Ui.text(a,ep.title,16,true);t.setPadding(Ui.dp(a,12),0,Ui.dp(a,12),0);r.addView(t,new LinearLayout.LayoutParams(0,-1,1));TextView p=Ui.text(a,"▶",25,true);p.setTextColor(Ui.ACCENT);p.setGravity(Gravity.CENTER);r.addView(p,new LinearLayout.LayoutParams(Ui.dp(a,55),-1));r.setOnClickListener(x->detail(ep));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,Ui.dp(a,84));lp.bottomMargin=Ui.dp(a,7);content.addView(r,lp);}});}
        void episodeLinks(int id,JSONObject d,String name,ArrayList<Link> watch,ArrayList<Link> down){if(!watch.isEmpty())linkButtons("سيرفرات المشاهدة",watch,name,false);if(!down.isEmpty())linkButtons("سيرفرات التنزيل",down,name,true);if(watch.isEmpty())OscarApi.get("api/watch_links/",OscarApi.params("episode_id",id),(v,e)->{if(e==null){ArrayList<Link> x=linksDeep(v);if(!x.isEmpty())linkButtons("سيرفرات المشاهدة",x,name,false);}});if(down.isEmpty())OscarApi.get("api/download_links/",OscarApi.params("episode_id",id),(v,e)->{if(e==null){ArrayList<Link> x=linksDeep(v);if(!x.isEmpty())linkButtons("سيرفرات التنزيل",x,name,true);}});}
        void linkButtons(String head,ArrayList<Link> ls,String title,boolean download){if(ls==null||ls.isEmpty())return;title(head);for(int x=0;x<ls.size();x++){final Link l=ls.get(x);String label=(l.name.isEmpty()?"سيرفر "+(x+1):l.name)+(l.quality.isEmpty()?"":" · "+l.quality);TextView b=Ui.button(a,(download?"↓  ":"▶  ")+label,v->openLink(l,title,download));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,Ui.dp(a,52));lp.bottomMargin=Ui.dp(a,6);content.addView(b,lp);}}
        void openLink(Link l,String title,boolean download){String u=OscarApi.absolute(l.url);if(u.isEmpty())u=l.deep;if(u==null||u.isEmpty()){Toast.makeText(a,"رابط السيرفر غير متاح",Toast.LENGTH_SHORT).show();return;}if(!(u.startsWith("http://")||u.startsWith("https://"))){try{a.startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(u)));}catch(Exception e){Toast.makeText(a,"تعذر فتح هذا السيرفر",Toast.LENGTH_SHORT).show();}return;}try{JSONObject s=new JSONObject();s.put("url",u);s.put("type",l.type);s.put("premium","0");s.put("size","https://oscartv.app/");Media.open(a,s,title,download);}catch(Exception e){Toast.makeText(a,"تعذر تجهيز السيرفر",Toast.LENGTH_SHORT).show();}}
    }

    static ArrayList<Item> filter(ArrayList<Item> all,String k){ArrayList<Item> x=new ArrayList<>();for(Item i:all)if(k.equals(i.kind))x.add(i);return x;}
    static ArrayList<Item> unique(ArrayList<Item> a){LinkedHashMap<String,Item> m=new LinkedHashMap<>();for(Item i:a)m.put(i.kind+":"+i.id,m.containsKey(i.kind+":"+i.id)?m.get(i.kind+":"+i.id):i);return new ArrayList<>(m.values());}
    static ArrayList<Item> collect(Object v,String forced,int max){ArrayList<Item> out=new ArrayList<>();collect0(v,forced,out,0,max);return unique(out);}
    static void collect0(Object v,String forced,ArrayList<Item> out,int depth,int max){if(v==null||v==JSONObject.NULL||depth>9||out.size()>=max)return;if(v instanceof JSONArray){JSONArray a=(JSONArray)v;for(int i=0;i<a.length();i++)collect0(a.opt(i),forced,out,depth+1,max);return;}if(!(v instanceof JSONObject))return;JSONObject o=(JSONObject)v;Item i=normalize(o,forced);if(i.id>0&&!i.title.equals("بدون عنوان"))out.add(i);Iterator<String> it=o.keys();while(it.hasNext()){String k=it.next();Object n=o.opt(k);String f=forced;if(k.contains("movie"))f="movie";else if(k.contains("series"))f="series";else if(k.contains("anime"))f="anime";else if(k.contains("channel"))f="channel";else if(k.contains("episode"))f="episode";if(n instanceof JSONArray||n instanceof JSONObject)collect0(n,f,out,depth+1,max);}}
    static Item normalize(JSONObject o,String forced){Item x=new Item();x.raw=o;x.id=intv(o,"id","item_id","series_id","movie_id","anime_id","channel_id","episode_id");x.kind=forced==null?guess(o):forced;x.title=pick(o,"title_ar","name_ar","name","title","anime_title","series_title","title_en","name_en");if(x.kind.equals("season")){int n=intv(o,"season_number");x.title=pick(o,"title");if(x.title.isEmpty())x.title="الموسم "+(n>0?n:x.id);}if(x.kind.equals("episode")){int n=intv(o,"episode_number");if(n>0)x.title="الحلقة "+n+(x.title.isEmpty()?"":" · "+x.title);}x.poster=pick(o,"poster","thumbnail","logo","anime_poster","series_poster","image");x.banner=pick(o,"banner","cover","anime_banner","series_banner","backdrop");x.sub=join(pick(o,"release_year","country_name","country"),pick(o,"rating","quality_source","status"));return x;}
    static String guess(JSONObject o){if(o.has("stream_url")||o.has("streams")||o.has("logo")&&o.has("country"))return "channel";if(o.has("episode_number")||o.has("series_id")&&o.has("season_id"))return "episode";if(o.has("anime_type")||o.has("anime_title"))return "anime";if(o.has("runtime")||o.has("quality_source")||o.has("tmdb_id"))return "movie";if(o.has("season_number")&&!o.has("episode_number"))return "season";return "series";}
    static ArrayList<Item> itemsFromArray(JSONArray a,String k){return a==null?new ArrayList<>():collect(a,k,100);}
    static int intv(JSONObject o,String...ks){for(String k:ks){Object v=o.opt(k);if(v instanceof Number)return ((Number)v).intValue();try{if(v instanceof String)return Integer.parseInt((String)v);}catch(Exception ignored){}}return 0;}
    static String pick(JSONObject o,String...ks){for(String k:ks){String v=o.optString(k,"").trim();if(!v.isEmpty()&&!"null".equals(v))return v;}return "";}
    static String pick(JSONObject o,String k1,String k2,String k3,String fallback1,String fallback2){String x=pick(o,k1,k2,k3);return x.isEmpty()?(!fallback1.isEmpty()?fallback1:fallback2):x;}
    static String join(String a,String b){if(a==null)a="";if(b==null)b="";return a.isEmpty()?b:b.isEmpty()?a:a+"  •  "+b;}
    static JSONObject findObject(Object v){if(v instanceof JSONObject){JSONObject o=(JSONObject)v;Object d=o.opt("data");if(d instanceof JSONObject)return (JSONObject)d;if(o.has("id"))return o;Iterator<String> it=o.keys();while(it.hasNext()){Object n=o.opt(it.next());JSONObject f=findObject(n);if(f!=null)return f;}}else if(v instanceof JSONArray){JSONArray a=(JSONArray)v;for(int i=0;i<a.length();i++){JSONObject f=findObject(a.opt(i));if(f!=null)return f;}}return null;}
    static JSONArray findArrayByKey(Object v,String key){if(v instanceof JSONObject){JSONObject o=(JSONObject)v;JSONArray a=o.optJSONArray(key);if(a!=null)return a;Iterator<String> it=o.keys();while(it.hasNext()){Object n=o.opt(it.next());JSONArray r=findArrayByKey(n,key);if(r!=null)return r;}}else if(v instanceof JSONArray){JSONArray a=(JSONArray)v;for(int i=0;i<a.length();i++){JSONArray r=findArrayByKey(a.opt(i),key);if(r!=null)return r;}}return null;}
    static ArrayList<Link> links(Object v){ArrayList<Link> out=new ArrayList<>();links0(v,out,0);return out;}
    static ArrayList<Link> linksDeep(Object v){return links(v);}
    static void links0(Object v,ArrayList<Link> out,int depth){if(v==null||v==JSONObject.NULL||depth>7)return;if(v instanceof JSONArray){JSONArray a=(JSONArray)v;for(int i=0;i<a.length();i++)links0(a.opt(i),out,depth+1);return;}if(!(v instanceof JSONObject))return;JSONObject o=(JSONObject)v;String url=pick(o,"url","stream_url","play_url"),deep=pick(o,"deep_link");if(!url.isEmpty()||!deep.isEmpty()){Link l=new Link();l.url=url;l.deep=deep;l.name=pick(o,"server_name","name");l.quality=pick(o,"quality","file_size");l.type=pick(o,"type","stream_type");out.add(l);return;}Iterator<String> it=o.keys();while(it.hasNext()){Object n=o.opt(it.next());if(n instanceof JSONArray||n instanceof JSONObject)links0(n,out,depth+1);}}
}
