package awr.witcher;

import android.app.*;
import android.content.*;
import android.graphics.*;
import android.graphics.drawable.*;
import android.os.*;
import android.text.*;
import android.view.*;
import android.view.inputmethod.EditorInfo;
import android.widget.*;
import org.json.*;
import java.util.*;

/** Source World is a self-contained navigation surface over the existing host. */
final class OscarExperience {
    static final String[] TAB_KEYS={"home","series","movie","channel","match","anime","wrestling","favorites","search","settings","main"};
    static final String[] TAB_NAMES={"الرئيسية","المسلسلات","الأفلام","القنوات","المباريات","أنمي","المصارعة","المفضلة","بحث","الإعدادات","التبويبات الرئيسية"};
    static final String[] TAB_ICONS={"oscar","series","movies","channels","ball","anime","wrestling","heart","search","settings","back"};
    static void open(Context context){Context c=context;while(c instanceof ContextWrapper&&!(c instanceof Activity))c=((ContextWrapper)c).getBaseContext();if(c instanceof Activity)new Screen((Activity)c).show();}
    static class State {String page="home",kind="series",title="عالم المصادر",search="";int scroll;OscarCatalog.Item item;Map<String,String> filters=new LinkedHashMap<>();}
    static final class Screen {
        final Activity a;final Handler handler=new Handler(Looper.getMainLooper());final ArrayDeque<State> history=new ArrayDeque<>();
        final SharedPreferences prefs;Dialog dialog;LinearLayout root,content;ScrollView scroll;HorizontalScrollView tabs;State state=new State();String active="home";int generation;
        Screen(Activity activity){a=activity;OscarApi.initialize(a);prefs=a.getSharedPreferences("awr_sources",0);}
        void show(){dialog=new Dialog(a,android.R.style.Theme_Material_NoActionBar);dialog.setOnDismissListener(d->{generation++;handler.removeCallbacksAndMessages(null);});dialog.setOnKeyListener((d,key,event)->{if(key!=KeyEvent.KEYCODE_BACK)return false;if(event.getAction()==KeyEvent.ACTION_UP)back();return true;});render();dialog.show();Window w=dialog.getWindow();if(w!=null){w.setLayout(-1,-1);w.setBackgroundDrawable(new ColorDrawable(Ui.bg(a)));w.setStatusBarColor(Ui.bg(a));w.setNavigationBarColor(Ui.bg(a));}}
        void back(){if(history.isEmpty()){dialog.dismiss();return;}state=history.removeLast();render();}
        void navigate(State next){state.scroll=scroll.getScrollY();history.addLast(state);state=next;render();}
        void select(String key){if(key.equals("main")){dialog.dismiss();return;}history.clear();active=key;state=new State();state.page=key.equals("home")||key.equals("favorites")||key.equals("search")||key.equals("settings")?key:key.equals("match")?"matches":"list";state.kind=key;state.title=tabName(key);render();}
        String tabName(String key){for(int i=0;i<TAB_KEYS.length;i++)if(TAB_KEYS[i].equals(key))return TAB_NAMES[i];return "عالم المصادر";}
        boolean current(int token){return token==generation&&!a.isFinishing()&&!a.isDestroyed();}
        void render(){generation++;handler.removeCallbacksAndMessages(null);root=Ui.column(a);root.setBackgroundColor(Ui.bg(a));root.addView(top(),new LinearLayout.LayoutParams(-1,Ui.dp(a,62)));scroll=new ScrollView(a);scroll.setFillViewport(true);content=Ui.column(a);content.setPadding(Ui.dp(a,12),0,Ui.dp(a,12),Ui.dp(a,24));scroll.addView(content);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));tabs=nav();root.addView(tabs,new LinearLayout.LayoutParams(-1,Ui.dp(a,72)));dialog.setContentView(root);
            switch(state.page){case "home":home();break;case "list":catalogue();break;case "detail":detail();break;case "matches":matches();break;case "favorites":favorites();break;case "search":search();break;case "settings":settings();break;}
        }
        View top(){LinearLayout r=Ui.row(a);r.setPadding(Ui.dp(a,4),0,Ui.dp(a,4),0);r.setBackgroundColor(Ui.surface(a));TextView b=text(history.isEmpty()?"⌂":"›",30,true);b.setGravity(Gravity.CENTER);b.setContentDescription(history.isEmpty()?"التبويبات الرئيسية":"رجوع");b.setOnClickListener(v->back());r.addView(b,new LinearLayout.LayoutParams(Ui.dp(a,48),-1));LinearLayout title=Ui.column(a);TextView t=text(state.title,18,true);t.setMaxLines(1);t.setEllipsize(TextUtils.TruncateAt.END);title.addView(t);TextView sub=text("AWR WORLD  /  عالم المصادر",10,true);sub.setTextColor(Ui.ACCENT);title.addView(sub);r.addView(title,new LinearLayout.LayoutParams(0,-2,1));Ui.Icon icon=new Ui.Icon(a,"search",Ui.ACCENT);icon.setPadding(12,12,12,12);icon.setContentDescription("البحث في كل المصادر");icon.setOnClickListener(v->select("search"));r.addView(icon,new LinearLayout.LayoutParams(Ui.dp(a,46),Ui.dp(a,46)));return r;}
        HorizontalScrollView nav(){HorizontalScrollView h=new HorizontalScrollView(a);h.setHorizontalScrollBarEnabled(true);h.setBackgroundColor(Ui.surface(a));h.setLayoutDirection(View.LAYOUT_DIRECTION_RTL);LinearLayout row=Ui.row(a);View selected=null;for(int i=0;i<TAB_KEYS.length;i++){final String key=TAB_KEYS[i];boolean on=active.equals(key);LinearLayout cell=Ui.column(a);cell.setGravity(Gravity.CENTER);cell.setSelected(on);cell.setContentDescription(TAB_NAMES[i]);Ui.clickable(cell,on?0x20eec60a:Color.TRANSPARENT,12);cell.addView(new Ui.Icon(a,TAB_ICONS[i],on?Ui.ACCENT:Ui.muted(a)),new LinearLayout.LayoutParams(Ui.dp(a,23),Ui.dp(a,23)));TextView label=text(TAB_NAMES[i],11,on);label.setTextColor(on?Ui.ACCENT:Ui.muted(a));label.setGravity(Gravity.CENTER);cell.addView(label);cell.setOnClickListener(v->select(key));row.addView(cell,new LinearLayout.LayoutParams(Ui.dp(a,key.equals("main")?125:83),Ui.dp(a,67)));if(on)selected=cell;}h.addView(row);View target=selected;if(target!=null)h.post(()->h.smoothScrollTo(Math.max(0,target.getLeft()-(h.getWidth()-target.getWidth())/2),0));return h;}
        TextView text(String s,int size,boolean bold){TextView t=Ui.text(a,s,size+(prefs.getBoolean("large_text",false)?2:0),bold);return t;}
        void heading(LinearLayout parent,String s){TextView t=text(s,20,true);t.setPadding(2,Ui.dp(a,20),2,Ui.dp(a,12));parent.addView(t);}
        void note(LinearLayout parent,String s){TextView t=text(s,14,false);t.setTextColor(Ui.muted(a));t.setPadding(Ui.dp(a,8),Ui.dp(a,18),Ui.dp(a,8),Ui.dp(a,18));parent.addView(t);}
        TextView button(LinearLayout parent,String s,Runnable task){TextView t=Ui.button(a,s,v->task.run());LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.topMargin=p.bottomMargin=Ui.dp(a,4);parent.addView(t,p);return t;}
        View loading(LinearLayout p){ProgressBar v=new ProgressBar(a);v.setIndeterminateTintList(android.content.res.ColorStateList.valueOf(Ui.ACCENT));LinearLayout.LayoutParams l=new LinearLayout.LayoutParams(Ui.dp(a,36),Ui.dp(a,36));l.gravity=Gravity.CENTER;l.topMargin=l.bottomMargin=Ui.dp(a,30);p.addView(v,l);return v;}
        void error(LinearLayout parent,String message,Runnable retry){parent.removeAllViews();heading(parent,"تعذر تحميل المحتوى");note(parent,message);button(parent,"إعادة المحاولة",retry);}
        void home(){int token=generation;View wait=loading(content);OscarApi.get("api/v2/home.php",OscarApi.params("app_version","14"),(r,e)->{if(!current(token))return;content.removeView(wait);if(e!=null){error(content,e,this::render);return;}JSONObject d=r.optJSONObject("data");if(d==null){error(content,"لم يرسل المصدر بيانات الرئيسية.",this::render);return;}List<OscarCatalog.Item> banners=OscarCatalog.banners(d);if(!banners.isEmpty())hero(banners);JSONArray sections=d.optJSONArray("sections");if(sections!=null)for(int i=0;i<sections.length();i++){JSONObject o=sections.optJSONObject(i);if(o==null)continue;OscarCatalog.Section section=new OscarCatalog.Section(o);if(!section.items.isEmpty())rail(section);}if(content.getChildCount()==0)note(content,"لا توجد أقسام متاحة حالياً.");restoreScroll();});}
        void hero(List<OscarCatalog.Item> items){ViewFlipper pager=new ViewFlipper(a);for(OscarCatalog.Item item:items){FrameLayout frame=new FrameLayout(a);frame.addView(Ui.image(a,item.banner.isEmpty()?item.poster:item.banner,20),new FrameLayout.LayoutParams(-1,-1));LinearLayout overlay=Ui.column(a);overlay.setGravity(Gravity.BOTTOM);overlay.setPadding(Ui.dp(a,18),0,Ui.dp(a,18),Ui.dp(a,20));overlay.setBackground(new GradientDrawable(GradientDrawable.Orientation.TOP_BOTTOM,new int[]{0x00000000,0xec101116}));TextView badge=text("عالم المصادر",12,true);badge.setTextColor(Ui.ACCENT);overlay.addView(badge);overlay.addView(text(item.title,26,true));overlay.addView(text(item.subtitle,12,false));TextView open=text("اكتشف الآن  ◀",14,true);open.setTextColor(Ui.ACCENT);overlay.addView(open);frame.addView(overlay,new FrameLayout.LayoutParams(-1,-1));frame.setOnClickListener(v->open(item));pager.addView(frame);}final float[] start={0};pager.setOnTouchListener((v,event)->{if(event.getAction()==MotionEvent.ACTION_DOWN){start[0]=event.getX();return true;}if(event.getAction()==MotionEvent.ACTION_UP){float dx=event.getX()-start[0];if(Math.abs(dx)>Ui.dp(a,40)){if(dx>0)pager.showNext();else pager.showPrevious();}else open(items.get(pager.getDisplayedChild()));return true;}return true;});content.addView(pager,new LinearLayout.LayoutParams(-1,Ui.dp(a,310)));if(items.size()>1){TextView dots=text("‹   اسحب لاستعراض الأعمال   ›",11,false);dots.setGravity(Gravity.CENTER);content.addView(dots);}if(prefs.getBoolean("auto_banner",true)&&items.size()>1){int token=generation;handler.postDelayed(new Runnable(){public void run(){if(!current(token))return;pager.showNext();handler.postDelayed(this,6500);}},6500);}}
        void rail(OscarCatalog.Section section){LinearLayout h=Ui.row(a);TextView label=text(section.title,19,true);h.addView(label,new LinearLayout.LayoutParams(0,Ui.dp(a,56),1));if(section.more){TextView all=text("عرض الكل",12,true);all.setTextColor(Ui.ACCENT);all.setPadding(12,12,12,12);all.setOnClickListener(v->list(section.kind,section.title,section.filters,""));h.addView(all);}content.addView(h);HorizontalScrollView sc=new HorizontalScrollView(a);LinearLayout row=Ui.row(a);for(OscarCatalog.Item item:section.items){View card=card(item);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(Ui.dp(a,124),Ui.dp(a,228));p.setMargins(5,0,5,0);row.addView(card,p);}sc.addView(row);sc.setHorizontalScrollBarEnabled(false);content.addView(sc);}
        View card(OscarCatalog.Item item){LinearLayout card=Ui.column(a);Ui.clickable(card,Ui.surface(a),14);card.addView(Ui.image(a,item.poster,14),new LinearLayout.LayoutParams(-1,0,1));TextView title=text(item.title,12,true);title.setMaxLines(2);title.setEllipsize(TextUtils.TruncateAt.END);title.setPadding(8,8,8,4);card.addView(title,new LinearLayout.LayoutParams(-1,Ui.dp(a,46)));TextView sub=text(item.subtitle,10,false);sub.setTextColor(Ui.muted(a));sub.setMaxLines(1);sub.setPadding(8,0,8,4);card.addView(sub,new LinearLayout.LayoutParams(-1,Ui.dp(a,22)));card.setOnClickListener(v->open(item));return card;}
        void grid(LinearLayout parent,List<OscarCatalog.Item> items){int columns=Math.max(2,Math.min(5,(int)(a.getResources().getDisplayMetrics().widthPixels/a.getResources().getDisplayMetrics().density)/125));LinearLayout row=null;for(int i=0;i<items.size();i++){if(i%columns==0){row=Ui.row(a);parent.addView(row,new LinearLayout.LayoutParams(-1,Ui.dp(a,238)));}LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,Ui.dp(a,228),1);p.setMargins(5,5,5,5);row.addView(card(items.get(i)),p);}if(row!=null)while(row.getChildCount()<columns)row.addView(new View(a),new LinearLayout.LayoutParams(0,1,1));}
        void list(String kind,String title,Map<String,String> filters,String search){State n=new State();n.page="list";n.kind=kind;n.title=title;n.filters.putAll(filters);n.search=search;navigate(n);}
        void catalogue(){if(!state.kind.contains("episode")){TextView f=button(content,"التصنيفات والفلاتر",this::filters);f.setTextColor(Ui.ACCENT);}else{TextView sort=button(content,"ترتيب الحلقات: "+("desc".equals(state.filters.get("sort"))?"الأحدث أولاً":"الأقدم أولاً"),()->{state.filters.put("sort","desc".equals(state.filters.get("sort"))?"asc":"desc");render();});}EditText input=input(state.kind.contains("episode")?"بحث برقم الحلقة أو اسمها":"بحث في "+state.title,state.search);content.addView(input);input.setOnEditorActionListener((v,id,event)->{if(id==EditorInfo.IME_ACTION_SEARCH){state.search=input.getText().toString().trim();render();return true;}return false;});if(!state.filters.isEmpty())button(content,"إزالة الفلاتر",()->{String season=state.filters.get("season_id");state.filters.clear();if(season!=null)state.filters.put("season_id",season);render();});LinearLayout results=Ui.column(a);content.addView(results);new Pager(results,state.kind,state.search,state.filters).next();}
        final class Pager {final LinearLayout parent;final String kind,search;final Map<String,String> filters;final Set<String> seen=new HashSet<>();final int token=generation;int next=1;boolean busy;Pager(LinearLayout p,String k,String q,Map<String,String> f){parent=p;kind=k;search=q;filters=new LinkedHashMap<>(f);}void next(){if(busy)return;busy=true;View wait=loading(parent);OscarApi.get(OscarCatalog.listRoute(kind),OscarCatalog.query(kind,search,next,filters),(r,e)->{if(!current(token))return;busy=false;parent.removeView(wait);if(e!=null){LinearLayout fail=Ui.column(a);parent.addView(fail);error(fail,e,()->{parent.removeView(fail);next();});return;}OscarCatalog.Page page=new OscarCatalog.Page(r,kind,next);List<OscarCatalog.Item> fresh=new ArrayList<>();for(OscarCatalog.Item i:page.items)if(seen.add(i.key()))fresh.add(i);if(next==1&&fresh.isEmpty())note(parent,"لا توجد نتائج لهذا الاختيار.");grid(parent,fresh);if(page.more()){next=page.page+1;TextView more=Ui.button(a,"تحميل المزيد",null);more.setOnClickListener(v->{parent.removeView(more);next();});parent.addView(more,new LinearLayout.LayoutParams(-1,Ui.dp(a,52)));}restoreScroll();});}}
        EditText input(String hint,String value){EditText t=new EditText(a);t.setTextColor(Ui.textColor(a));t.setHintTextColor(Ui.muted(a));t.setSingleLine(true);t.setTextSize(15);t.setText(value);t.setHint(hint);t.setImeOptions(EditorInfo.IME_ACTION_SEARCH);t.setPadding(Ui.dp(a,14),Ui.dp(a,12),Ui.dp(a,14),Ui.dp(a,12));t.setBackground(Ui.rounded(a,Ui.surface(a),12));return t;}
        void search(){EditText input=input("اسم فيلم، مسلسل، أنمي أو قناة",state.search);content.addView(input);Runnable run=()->{state.search=input.getText().toString().trim();render();};input.setOnEditorActionListener((v,id,event)->{if(id==EditorInfo.IME_ACTION_SEARCH){run.run();return true;}return false;});button(content,"بحث",run);if(state.search.isEmpty()){note(content,"ابحث في كتالوج المصدر، بما فيه الأعمال التي لا تظهر في الرئيسية.");return;}for(String kind:new String[]{"series","movie","anime","channel","wrestling"}){heading(content,tabName(kind));LinearLayout group=Ui.column(a);content.addView(group);new Pager(group,kind,state.search,Collections.emptyMap()).next();}}
        void filters(){String kind=state.kind;String path=kind.equals("wrestling")?"api/wrestling/categories.php":kind.equals("channel")?"api/channels/collections.php":OscarCatalog.listRoute(kind)+"filters.php";int token=generation;Map<String,String> query=kind.equals("series")?OscarApi.params("app_version","14"):OscarApi.params();OscarApi.get(path,query,(r,e)->{if(!current(token))return;if(e!=null){alert(e);return;}JSONObject data=r.optJSONObject("data");if(data==null){JSONArray rows=r.optJSONArray("data");if(kind.equals("wrestling")){chooseFilter("category_id","نوع المصارعة",rows);return;}alert("لم يرسل المصدر خيارات الفلاتر.");return;}String[] keys={"categories","genres","countries","years","statuses","languages","content_types","age_ratings","sources","sort_options","studios","anime_types","season_periods"};String[] labels={"التصنيف: آسيوي، تركي، أجنبي…","النوع","الدولة","السنة","الحالة","اللغة","مترجم / مدبلج","التصنيف العمري","جودة المصدر","الترتيب","الاستديو","نوع الأنمي","موسم العرض"};String[] queryKeys={"category","genre_id","country","year","status","language","content_type","age_rating","quality_source","sort_by","studio_id","anime_type","season_period"};List<String> names=new ArrayList<>();List<Integer> indices=new ArrayList<>();for(int i=0;i<keys.length;i++)if(data.optJSONArray(keys[i])!=null){names.add(labels[i]);indices.add(i);}if(names.isEmpty()){alert("لا توجد فلاتر متاحة لهذا القسم.");return;}new AlertDialog.Builder(a).setTitle("تصفية المحتوى").setItems(names.toArray(new String[0]),(d,w)->{int i=indices.get(w);chooseFilter(queryKeys[i],labels[i],data.optJSONArray(keys[i]));}).setNegativeButton("إلغاء",null).show();});}
        void chooseFilter(String key,String title,JSONArray rows){if(rows==null)return;List<String> names=new ArrayList<>(),values=new ArrayList<>();names.add("الكل");values.add("");for(int i=0;i<rows.length();i++){Object x=rows.opt(i);String value,name;if(x instanceof JSONObject){JSONObject o=(JSONObject)x;value=OscarCatalog.text(o,key.equals("country")?"code":"id","value","key","slug","code");name=OscarCatalog.text(o,"name_ar","name","label","title_ar","name_en");}else{value=String.valueOf(x);name=value;}if(value.isEmpty())continue;names.add(name.isEmpty()?value:name);values.add(value);}new AlertDialog.Builder(a).setTitle(title).setItems(names.toArray(new String[0]),(d,w)->{if(values.get(w).isEmpty())state.filters.remove(key);else state.filters.put(key,values.get(w));render();}).setNegativeButton("إلغاء",null).show();}
        void open(OscarCatalog.Item item){State n=new State();n.page="detail";n.kind=item.kind;n.item=item;n.title=item.title;navigate(n);}
        void detail(){int token=generation;View wait=loading(content);OscarApi.get(OscarCatalog.detailRoute(state.kind),OscarApi.params("id",state.item.id),(r,e)->{if(!current(token))return;content.removeView(wait);if(e!=null){error(content,e,this::render);return;}JSONObject d=r.optJSONObject("data");if(d==null){error(content,"لم يرسل المصدر تفاصيل العمل.",this::render);return;}OscarCatalog.Item item=new OscarCatalog.Item(state.kind,d);drawDetail(item,token);});}
        void drawDetail(OscarCatalog.Item item,int token){JSONObject d=item.raw;String image=item.banner.isEmpty()?item.poster:item.banner;if(!image.isEmpty())content.addView(Ui.image(a,image,18),new LinearLayout.LayoutParams(-1,Ui.dp(a,240)));heading(content,item.title);note(content,OscarCatalog.join(item.subtitle,OscarCatalog.text(d,"rating").isEmpty()?"":"★ "+OscarCatalog.text(d,"rating")));TextView fav=button(content,isFavorite(item)?"♥ إزالة من المفضلة":"♡ أضف إلى المفضلة",()->{});fav.setTextColor(Ui.ACCENT);fav.setOnClickListener(v->{toggleFavorite(item);fav.setText(isFavorite(item)?"♥ إزالة من المفضلة":"♡ أضف إلى المفضلة");});if(!item.story.isEmpty())note(content,item.story);metadata(d,"genres","الأنواع");metadata(d,"actors","فريق العمل");metadata(d,"characters","الشخصيات");
            if(item.kind.equals("series")||item.kind.equals("anime")){JSONArray seasons=d.optJSONArray("seasons");if(seasons!=null&&seasons.length()>0)seasons(item,seasons);else if(item.kind.equals("series")){LinearLayout block=Ui.column(a);content.addView(block);OscarApi.get("api/seasons/",OscarApi.params("series_id",item.id),(r,e)->{if(!current(token))return;if(e!=null){error(block,e,this::render);return;}seasons(item,r.optJSONArray("data"));});}}
            linksBlock(item,"watch_links","سيرفرات المشاهدة",false,token);linksBlock(item,"download_links","سيرفرات التنزيل",true,token);
            if(item.kind.equals("channel"))links(content,d.optJSONArray("streams"),item.title,false);
            if(item.kind.equals("match")){JSONArray channels=d.optJSONArray("channels");heading(content,"قنوات المباراة");if(channels!=null)for(int i=0;i<channels.length();i++){JSONObject ch=channels.optJSONObject(i);if(ch==null)continue;String name=OscarCatalog.text(ch,"channel_name");heading(content,name);links(content,ch.optJSONArray("streams"),item.title,false);String id=OscarCatalog.text(ch,"channel_id");if(!id.isEmpty()){JSONObject c=new JSONObject();try{c.put("id",id).put("name",name).put("logo",ch.opt("channel_logo"));}catch(JSONException ignored){}button(content,"فتح القناة",()->open(new OscarCatalog.Item("channel",c)));}}metadata(d,"statistics","إحصائيات المباراة");}
        }
        void metadata(JSONObject d,String key,String title){JSONArray a=d.optJSONArray(key);if(a==null||a.length()==0)return;List<String> names=new ArrayList<>();for(int i=0;i<a.length();i++){JSONObject o=a.optJSONObject(i);String s=o==null?a.optString(i):OscarCatalog.text(o,"name_ar","name","actor_name","character_name","type");if(!s.isEmpty())names.add(s);}if(!names.isEmpty()){heading(content,title);note(content,TextUtils.join(" • ",names));}}
        void seasons(OscarCatalog.Item series,JSONArray seasons){heading(content,"المواسم والحلقات");if(seasons==null||seasons.length()==0){note(content,"لا توجد مواسم متاحة حالياً.");return;}for(int i=0;i<seasons.length();i++){JSONObject s=seasons.optJSONObject(i);if(s==null)continue;String id=OscarCatalog.text(s,"id"),title=OscarCatalog.text(s,"title");if(id.isEmpty())continue;if(title.isEmpty())title="الموسم "+OscarCatalog.text(s,"season_number");final String label=title;button(content,title+"   •   "+OscarCatalog.text(s,"episodes_count")+" حلقة",()->list(series.kind.equals("anime")?"anime_episode":"episode",series.title+" / "+label,OscarApi.params("season_id",id,"sort","asc"),""));}}
        void linksBlock(OscarCatalog.Item item,String key,String label,boolean download,int token){JSONArray rows=item.raw.optJSONArray(key);if(rows!=null){if(rows.length()>0){heading(content,label);links(content,rows,item.title,download);}return;}if(!item.kind.equals("episode"))return;LinearLayout block=Ui.column(a);content.addView(block);OscarApi.get(download?"api/download_links/":"api/watch_links/",OscarApi.params("episode_id",item.id),(r,e)->{if(!current(token))return;if(e!=null){note(block,e);return;}JSONArray found=r.optJSONArray("data");if(found!=null&&found.length()>0){heading(block,label);links(block,found,item.title,download);}});}
        void links(LinearLayout parent,JSONArray rows,String title,boolean download){if(rows==null)return;for(int i=0;i<rows.length();i++){JSONObject source=rows.optJSONObject(i);if(source==null)continue;String name=OscarCatalog.text(source,"server_name"),quality=OscarCatalog.text(source,"quality"),size=OscarCatalog.text(source,"file_size");if(name.isEmpty())name="سيرفر "+(i+1);button(parent,(download?"↓  ":"▶  ")+OscarCatalog.join(name,quality,size),()->OscarMedia.open(a,source,title,download));}}
        void matches(){Calendar today=Calendar.getInstance();String date=state.filters.get("date");if(date==null)date=new java.text.SimpleDateFormat("yyyy-MM-dd",Locale.US).format(today.getTime());final String chosen=date;button(content,"📅  "+date,()->new DatePickerDialog(a,(v,y,m,d)->{state.filters.put("date",String.format(Locale.US,"%04d-%02d-%02d",y,m+1,d));render();},today.get(Calendar.YEAR),today.get(Calendar.MONTH),today.get(Calendar.DAY_OF_MONTH)).show());LinearLayout block=Ui.column(a);content.addView(block);View wait=loading(block);int token=generation;OscarApi.get("api/matches/",OscarApi.params("date",chosen),(r,e)->{if(!current(token))return;block.removeView(wait);if(e!=null){error(block,e,this::render);return;}JSONObject data=r.optJSONObject("data");List<OscarCatalog.Item> items=data==null?Collections.emptyList():OscarCatalog.matches(data);if(items.isEmpty())note(block,"لا توجد مباريات في هذا التاريخ.");for(OscarCatalog.Item item:items){String score=OscarCatalog.join(OscarCatalog.text(item.raw,"match_time"),OscarCatalog.text(item.raw,"status"),item.raw.optInt("home_goals")+" : "+item.raw.optInt("away_goals"));button(block,item.title+"\n"+score,()->open(item));}button(block,"تحديث النتائج",this::render);});}
        JSONObject favoriteData(){try{return new JSONObject(prefs.getString("favorites","{}"));}catch(JSONException e){return new JSONObject();}}
        boolean isFavorite(OscarCatalog.Item i){return favoriteData().has(i.key());}
        void toggleFavorite(OscarCatalog.Item item){JSONObject data=favoriteData();if(data.has(item.key()))data.remove(item.key());else try{JSONObject entry=new JSONObject().put("kind",item.kind).put("data",item.raw);data.put(item.key(),entry);}catch(JSONException ignored){}prefs.edit().putString("favorites",data.toString()).apply();}
        void favorites(){JSONObject data=favoriteData();List<OscarCatalog.Item> items=new ArrayList<>();Iterator<String> it=data.keys();while(it.hasNext()){JSONObject v=data.optJSONObject(it.next());if(v!=null&&v.optJSONObject("data")!=null)items.add(new OscarCatalog.Item(v.optString("kind"),v.optJSONObject("data")));}heading(content,"قائمتي");if(items.isEmpty())note(content,"أضف الأعمال من صفحة التفاصيل لتجدها هنا.");else grid(content,items);}
        void settings(){heading(content,"إعدادات عالم المصادر");note(content,"عالم AWR • عالم المصادر\nالمشغل المفضل: MX Player\nالثيم الافتراضي: ليلي");Switch banner=new Switch(a);banner.setText("تبديل صور الرئيسية تلقائياً");banner.setTextColor(Ui.textColor(a));banner.setChecked(prefs.getBoolean("auto_banner",true));banner.setOnCheckedChangeListener((b,c)->prefs.edit().putBoolean("auto_banner",c).apply());content.addView(banner,new LinearLayout.LayoutParams(-1,Ui.dp(a,56)));Switch font=new Switch(a);font.setText("خط أكبر");font.setTextColor(Ui.textColor(a));font.setChecked(prefs.getBoolean("large_text",false));font.setOnCheckedChangeListener((b,c)->prefs.edit().putBoolean("large_text",c).apply());content.addView(font,new LinearLayout.LayoutParams(-1,Ui.dp(a,56)));button(content,"التنزيلات",()->{try{a.startActivity(new Intent(android.app.DownloadManager.ACTION_VIEW_DOWNLOADS));}catch(ActivityNotFoundException e){alert("لا يوجد مدير تنزيلات على الجهاز.");}});button(content,"التبويبات الرئيسية",()->dialog.dismiss());}
        void restoreScroll(){int y=state.scroll;if(y>0)scroll.post(()->scroll.scrollTo(0,y));}
        void alert(String text){if(!a.isFinishing())new AlertDialog.Builder(a).setMessage(text).setPositiveButton("حسناً",null).show();}
    }
}
