package awr.witcher;

import android.app.*;
import android.content.*;
import android.net.Uri;
import org.json.*;
import java.io.*;
import java.net.*;
import java.util.*;
import java.util.regex.*;

/** Resolve ordinary source media before MX; never send HTML or opaque app links to it. */
final class OscarMedia {
    static final String MX="com.mxtech.videoplayer.ad";
    static final class Stream {final String url,label,mime;final Map<String,String> headers;Stream(String u,String l,String m,Map<String,String> h){url=u;label=l;mime=m;headers=new LinkedHashMap<>(h);}}
    static boolean http(String u){try{URI uri=new URI(u);return (uri.getScheme().equalsIgnoreCase("http")||uri.getScheme().equalsIgnoreCase("https"))&&uri.getHost()!=null&&uri.getUserInfo()==null;}catch(Exception e){return false;}}
    static String sourceUrl(JSONObject source){String url=OscarCatalog.text(source,"url","stream_url");if(http(url))return url;String deep=OscarCatalog.text(source,"deep_link");return http(deep)?deep:"";}
    static Map<String,String> headers(JSONObject source){Map<String,String> h=new LinkedHashMap<>();JSONObject values=source.optJSONObject("headers");if(values!=null)for(String name:new String[]{"Referer","Origin","User-Agent","Cookie","Authorization"}){String v=OscarCatalog.text(values,name,name.toLowerCase(Locale.ROOT));if(!v.isEmpty()&&!v.contains("\r")&&!v.contains("\n"))h.put(name,v);}return h;}
    static void open(Activity a,JSONObject source,String title,boolean download){String url=sourceUrl(source);if(url.isEmpty()){fallback(a,source,"هذا السيرفر يقدّم رابطاً خاصاً بمشغل المصدر، وليس رابط فيديو جاهزاً لـ MX.");return;}ProgressDialog progress=new ProgressDialog(a);progress.setMessage("تجهيز الرابط والجودات…");progress.setCancelable(true);progress.show();final boolean[] cancelled={false};progress.setOnCancelListener(d->cancelled[0]=true);OscarApi.IO.execute(()->{List<Stream> streams=null;String error=null;try{streams=resolve(url,headers(source),0);}catch(Exception e){error=OscarApi.message(e);}final List<Stream> found=streams;final String issue=error;OscarApi.MAIN.post(()->{if(a.isFinishing()||a.isDestroyed())return;progress.dismiss();if(cancelled[0])return;if(issue!=null){fallback(a,source,issue);return;}if(found==null||found.isEmpty()){fallback(a,source,"لم يعطِ هذا السيرفر رابط فيديو مباشراً. يمكن فتح صفحة المصدر لإكمال خطواتها.");return;}if(found.size()>1){String[] names=new String[found.size()];for(int i=0;i<names.length;i++)names[i]=found.get(i).label;new AlertDialog.Builder(a).setTitle(download?"جودة التنزيل":"اختر الجودة").setItems(names,(d,w)->launch(a,found.get(w),title,download)).setNegativeButton("إلغاء",null).show();}else launch(a,found.get(0),title,download);});});}
    static List<Stream> resolve(String url,Map<String,String> headers,int depth)throws Exception{
        if(depth>3||!http(url))return Collections.emptyList();HttpURLConnection c=(HttpURLConnection)new URL(url).openConnection();c.setConnectTimeout(15000);c.setReadTimeout(18000);c.setInstanceFollowRedirects(false);for(Map.Entry<String,String> e:headers.entrySet())c.setRequestProperty(e.getKey(),e.getValue());
        try{int status=c.getResponseCode();if(status>=300&&status<400){String location=c.getHeaderField("Location");if(location==null)throw new IOException("رابط التحويل غير متاح.");String next=new URI(url).resolve(location).toString();Map<String,String> nextHeaders=new LinkedHashMap<>(headers);if(!sameOrigin(url,next)){nextHeaders.remove("Cookie");nextHeaders.remove("Authorization");}return resolve(next,nextHeaders,depth+1);}if(status<200||status>=300)throw new IOException(OscarApi.httpError(status));String mime=c.getContentType();mime=mime==null?"":mime.split(";")[0].trim().toLowerCase(Locale.ROOT);
            if(mime.startsWith("video/")&&!mime.contains("mpegurl"))return Collections.singletonList(new Stream(url,"الجودة الأصلية",mime,headers));
            if(mime.equals("application/dash+xml"))return Collections.singletonList(new Stream(url,"تلقائي • DASH",mime,headers));
            if((mime.equals("application/octet-stream")||mime.isEmpty())&&videoExtension(url))return Collections.singletonList(new Stream(url,"الجودة الأصلية","video/*",headers));
            String body=OscarApi.read(c.getInputStream(),2*1024*1024);if(body.trim().startsWith("#EXTM3U"))return hls(url,body,headers);
            List<Stream> parsed=htmlSources(url,body,headers);List<Stream> ready=new ArrayList<>();for(Stream stream:parsed){if(ready.size()>=12)break;List<Stream> child=resolve(stream.url,stream.headers,depth+1);for(Stream entry:child)ready.add(new Stream(entry.url,stream.label.equals("الجودة الأصلية")?entry.label:stream.label,entry.mime,entry.headers));}return ready;
        }finally{c.disconnect();}
    }
    static boolean sameOrigin(String a,String b)throws URISyntaxException{URI x=new URI(a),y=new URI(b);return Objects.equals(x.getScheme(),y.getScheme())&&Objects.equals(x.getHost(),y.getHost())&&x.getPort()==y.getPort();}
    static boolean videoExtension(String u){String path=Uri.parse(u).getPath();return path!=null&&path.toLowerCase(Locale.ROOT).matches(".*\\.(mp4|mkv|webm|mov|m4v|ts|avi)$");}
    static List<Stream> hls(String base,String body,Map<String,String> headers)throws URISyntaxException{List<Stream> out=new ArrayList<>();String pending=null;Set<String> urls=new HashSet<>();for(String raw:body.split("\\r?\\n")){String line=raw.trim();if(line.startsWith("#EXT-X-STREAM-INF:")){Matcher r=Pattern.compile("RESOLUTION=\\d+x(\\d+)").matcher(line);Matcher b=Pattern.compile("BANDWIDTH=(\\d+)").matcher(line);pending=r.find()?r.group(1)+"p":b.find()?(Long.parseLong(b.group(1))/1000)+" kb/s":"جودة إضافية";}else if(pending!=null&&!line.isEmpty()&&!line.startsWith("#")){String u=new URI(base).resolve(line).toString();if(http(u)&&urls.add(u))out.add(new Stream(u,pending,"application/x-mpegURL",headers));pending=null;}}
        // Keep the master as Auto: it retains alternate audio/subtitle rendition groups.
        if(out.isEmpty())out.add(new Stream(base,"الجودة الأصلية","application/x-mpegURL",headers));else out.add(0,new Stream(base,"تلقائي • جميع المسارات","application/x-mpegURL",headers));return out;
    }
    static List<Stream> htmlSources(String base,String body,Map<String,String> headers)throws URISyntaxException{List<Stream> list=new ArrayList<>();Set<String> seen=new HashSet<>();Matcher tags=Pattern.compile("<(?:source|video)\\b[^>]*>",Pattern.CASE_INSENSITIVE).matcher(body);Pattern attr=Pattern.compile("([a-zA-Z_-]+)\\s*=\\s*['\"]([^'\"]+)['\"]");while(tags.find()){Map<String,String> attrs=new HashMap<>();Matcher m=attr.matcher(tags.group());while(m.find())attrs.put(m.group(1).toLowerCase(Locale.ROOT),m.group(2));String src=attrs.get("src");if(src==null)continue;String u=new URI(base).resolve(src.replace("&amp;","&")).toString();if(!http(u)||!seen.add(u))continue;String label=attrs.get("label");if(label==null)label=attrs.get("size");if(label==null)label="الجودة الأصلية";Map<String,String> h=new LinkedHashMap<>(headers);if(!sameOrigin(base,u)){h.remove("Cookie");h.remove("Authorization");}h.put("Referer",base);list.add(new Stream(u,label,attrs.get("type"),h));}return list;}
    static Intent mxIntent(Stream stream,String title){Intent i=new Intent(Intent.ACTION_VIEW).setPackage(MX).setDataAndType(Uri.parse(stream.url),stream.mime==null?"video/*":stream.mime);ArrayList<String> h=new ArrayList<>();for(Map.Entry<String,String> e:stream.headers.entrySet()){h.add(e.getKey());h.add(e.getValue());}i.putExtra("headers",h.toArray(new String[0]));i.putExtra("title",title);return i;}
    static void launch(Activity a,Stream stream,String title,boolean download){if(download){DownloadFlow.open(a,stream.url,stream.headers,title,"application/x-mpegURL".equals(stream.mime)||"application/dash+xml".equals(stream.mime));return;}try{a.startActivity(mxIntent(stream,title));}catch(ActivityNotFoundException e){new AlertDialog.Builder(a).setMessage("ثبّت MX Player لفتح الفيديو.").setNegativeButton("إلغاء",null).setPositiveButton("فتح المتجر",(d,w)->external(a,"https://play.google.com/store/apps/details?id="+MX)).show();}}
    static void fallback(Activity a,JSONObject source,String message){String original=OscarCatalog.text(source,"deep_link","url","stream_url");AlertDialog.Builder b=new AlertDialog.Builder(a).setMessage(message).setNegativeButton("إغلاق",null);if(!original.isEmpty())b.setPositiveButton("فتح رابط المصدر",(d,w)->{Uri uri=Uri.parse(original);String scheme=uri.getScheme();if(scheme!=null&&!Arrays.asList("file","content","javascript","intent").contains(scheme.toLowerCase(Locale.ROOT)))external(a,original);});b.show();}
    static void external(Activity a,String url){try{a.startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(url)));}catch(Exception e){new AlertDialog.Builder(a).setMessage("لا يوجد تطبيق مناسب لفتح رابط المصدر.").setPositiveButton("حسناً",null).show();}}
}
