#!/usr/bin/env node
import crypto from 'node:crypto';
import fs from 'node:fs';
import https from 'node:https';
import tls from 'node:tls';

const HOST='web-api.hitvpro.com';
const BASES=['https://mobile-api.hitv.ltd','https://mobile-api.hitv.space','https://web-api.hitvpro.com'];
const PUBLIC_KEY_DER='MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCEZTSwZTZdBfQAm8oVroRdy6K7VVB0/7Jojx7e3UPa7NjjZ2A/mydH7QI9aHr3dNEJDrNLyZ/nEK6XzV+XTG3t3GVqsEjVOVO26K/VcDVwk/dFJs8bmK3AaIBPQATJQDztgSjg5H7u92JnyXvtj0XB0IH+GM2ui6sB69Y5T0LPAwIDAQAB';
const PUBLIC_KEY=`-----BEGIN PUBLIC KEY-----\n${PUBLIC_KEY_DER.match(/.{1,64}/g).join('\n')}\n-----END PUBLIC KEY-----`;
function flatten(params,nested=false){const values=[];for(const key of Object.keys(params)){const value=params[key];if(value==null)continue;if(Array.isArray(value)){value.forEach((entry,index)=>values.push(entry&&typeof entry==='object'?`${key}=${flatten(entry,true)}`:`${key}[${index}]=${String(entry)}`));}else if(typeof value==='object')values.push(`${key}=${flatten(value,true)}`);else values.push(`${key}=${String(value)}`);}if(nested)values.sort((a,b)=>a<b?1:a>b?-1:0);return Buffer.from(values.map(v=>v.slice(v.indexOf('=')+1)).join(''),'utf8').toString('base64');}
function headers(params,uuid){const currentTime=Date.now().toString();const payload=`${currentTime}${flatten(params,true)}`.replaceAll('+','-').replaceAll('/','_');const cipher=crypto.createCipheriv('aes-128-ecb',Buffer.from(uuid),null);const encrypted=Buffer.concat([cipher.update(payload,'utf8'),cipher.final()]).toString('base64');return {'Content-Type':'application/json','Accept':'application/json','lang':'ar',currentTime,sign:crypto.createHash('md5').update(encrypted).digest('hex'),aesKey:crypto.publicEncrypt({key:PUBLIC_KEY,padding:crypto.constants.RSA_PKCS1_PADDING},Buffer.from(uuid)).toString('base64'),'User-Agent':'Mozilla/5.0 (Linux; Android 15) AppleWebKit/537.36 Chrome/127.0 Mobile Safari/537.36'};}
function summarize(text,status){let code=null,encrypted=false;try{const j=JSON.parse(text);code=String(j.code??'');encrypted=typeof j.data==='string';}catch{}return {http:status,ok:status>=200&&status<300,code,encrypted_data:encrypted,response_bytes:Buffer.byteLength(text)};}
async function probe(base){const params={sequence:0,type:0},uuid=crypto.randomBytes(8).toString('hex');const url=new URL('/cms/web/hitv/homePage/album/page',base);Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,String(v)));const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),12000),started=Date.now();try{const r=await fetch(url,{headers:headers(params,uuid),redirect:'follow',signal:controller.signal});return {base,...summarize(await r.text(),r.status),elapsed_ms:Date.now()-started};}catch(e){return {base,http:null,ok:false,error:e?.cause?.code||e?.name||'network',elapsed_ms:Date.now()-started};}finally{clearTimeout(timer);}}
async function doh(){for(const endpoint of [`https://dns.google/resolve?name=${HOST}&type=A`,`https://cloudflare-dns.com/dns-query?name=${HOST}&type=A`]){try{const r=await fetch(endpoint,{headers:{Accept:'application/dns-json'},signal:AbortSignal.timeout(8000)});if(!r.ok)continue;const j=await r.json();const ips=(j.Answer||[]).filter(a=>a.type===1&&/^\d{1,3}(?:\.\d{1,3}){3}$/.test(a.data)).map(a=>a.data);if(ips.length)return ips;}catch{}}return [];}
async function probeIp(ip){const params={sequence:0,type:0},uuid=crypto.randomBytes(8).toString('hex'),h=headers(params,uuid);h.Host=HOST;const path='/cms/web/hitv/homePage/album/page?sequence=0&type=0';return await new Promise(resolve=>{const started=Date.now();const req=https.request({hostname:ip,port:443,path,method:'GET',headers:h,servername:HOST,rejectUnauthorized:true,checkServerIdentity:(host,cert)=>tls.checkServerIdentity(HOST,cert),timeout:12000},res=>{const chunks=[];res.on('data',c=>chunks.push(c));res.on('end',()=>resolve({ip,http_dns_bypass:true,...summarize(Buffer.concat(chunks).toString('utf8'),res.statusCode||0),elapsed_ms:Date.now()-started}));});req.on('timeout',()=>req.destroy(new Error('timeout')));req.on('error',e=>resolve({ip,http_dns_bypass:true,http:null,ok:false,error:e.code||e.name||'network',elapsed_ms:Date.now()-started}));req.end();});}
const report={generated_at:new Date().toISOString(),probes:[]};for(const base of BASES)report.probes.push(await probe(base));const ips=await doh();report.doh={host:HOST,address_count:ips.length,ip_probe:ips.length?await probeIp(ips[0]):null};fs.mkdirSync('diagnostics',{recursive:true});fs.writeFileSync('diagnostics/hitv-host-probe.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
