#!/usr/bin/env node
import crypto from 'node:crypto';
import fs from 'node:fs';
const BASE='https://web-api.hitvpro.com';
const DER='MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCEZTSwZTZdBfQAm8oVroRdy6K7VVB0/7Jojx7e3UPa7NjjZ2A/mydH7QI9aHr3dNEJDrNLyZ/nEK6XzV+XTG3t3GVqsEjVOVO26K/VcDVwk/dFJs8bmK3AaIBPQATJQDztgSjg5H7u92JnyXvtj0XB0IH+GM2ui6sB69Y5T0LPAwIDAQAB';
const KEY=`-----BEGIN PUBLIC KEY-----\n${DER.match(/.{1,64}/g).join('\n')}\n-----END PUBLIC KEY-----`;
function flatten(p,n=false){const a=[];for(const k of Object.keys(p)){const v=p[k];if(v==null)continue;if(Array.isArray(v))v.forEach((e,i)=>a.push(e&&typeof e==='object'?`${k}=${flatten(e,true)}`:`${k}[${i}]=${e}`));else if(typeof v==='object')a.push(`${k}=${flatten(v,true)}`);else a.push(`${k}=${v}`);}if(n)a.sort((x,y)=>x<y?1:x>y?-1:0);return Buffer.from(a.map(x=>x.slice(x.indexOf('=')+1)).join('')).toString('base64');}
function hdr(p,u){const t=Date.now().toString(),payload=(t+flatten(p,true)).replaceAll('+','-').replaceAll('/','_'),c=crypto.createCipheriv('aes-128-ecb',Buffer.from(u),null),enc=Buffer.concat([c.update(payload),c.final()]).toString('base64');return {'Content-Type':'application/json',Accept:'application/json',lang:'ar',currentTime:t,sign:crypto.createHash('md5').update(enc).digest('hex'),aesKey:crypto.publicEncrypt({key:KEY,padding:crypto.constants.RSA_PKCS1_PADDING},Buffer.from(u)).toString('base64'),'User-Agent':'Mozilla/5.0 (Linux; Android 15) AppleWebKit/537.36 Chrome/127.0 Mobile Safari/537.36'};}
function dec(s,u){const d=crypto.createDecipheriv('aes-128-ecb',Buffer.from(u),null);return Buffer.concat([d.update(Buffer.from(s,'base64')),d.final()]).toString('utf8');}
async function req(path,p={},method='GET'){const u=crypto.randomBytes(8).toString('hex'),url=new URL(path,BASE);if(method==='GET')for(const [k,v] of Object.entries(p))if(typeof v!=='object')url.searchParams.set(k,String(v));try{const r=await fetch(url,{method,headers:hdr(p,u),body:method==='POST'?JSON.stringify(p):undefined,signal:AbortSignal.timeout(15000)}),text=await r.text();let env={};try{env=JSON.parse(text);}catch{}let data=env.data;if(typeof data==='string')try{data=JSON.parse(dec(data,u));}catch{}return {http:r.status,code:String(env.code??''),message:String(env.msg??env.message??''),data};}catch(e){return {http:null,code:'',message:'',error:e?.cause?.code||e?.name||'network',data:null};}}
function collectItems(v,out=[],depth=0){if(!v||depth>8||out.length>40)return out;if(Array.isArray(v)){for(const e of v)collectItems(e,out,depth+1);return out;}if(typeof v!=='object')return out;const id=v.id??v.contentId??v.relatedId??v.relationId,name=v.name??v.title;if(id&&(name||v.coverVerticalUrl||v.coverHorizontalUrl)){const cv=v.domainType??v.category;out.push({id:String(id),category:(cv===0||cv==='0'||cv==='movie')?0:1,name:String(name??'')});}for(const e of Object.values(v))if(e&&typeof e==='object')collectItems(e,out,depth+1);return out;}
function mediaCount(v,seen=new Set(),depth=0){if(!v||depth>9)return 0;if(typeof v==='string')return /^https?:\/\//.test(v)&&!(/\.(jpg|jpeg|png|webp|gif|vtt|srt|ass)(\?|$)/i.test(v))?1:0;if(Array.isArray(v))return v.reduce((n,e)=>n+mediaCount(e,seen,depth+1),0);if(typeof v!=='object'||seen.has(v))return 0;seen.add(v);let n=0;for(const [k,e] of Object.entries(v)){if(['url','playUrl','mediaUrl','file','videoUrl','downloadUrl'].includes(k)&&typeof e==='string'&&/^https?:\/\//.test(e)&&!(/\.(jpg|jpeg|png|webp|gif|vtt|srt|ass)(\?|$)/i.test(e)))n++;else if(e&&typeof e==='object')n+=mediaCount(e,seen,depth+1);}return n;}
function shape(v,depth=0){if(v==null)return 'null';if(depth>3)return typeof v;if(Array.isArray(v))return {array_length:v.length,sample:v.length?shape(v[0],depth+1):null};if(typeof v==='object'){const o={};for(const k of Object.keys(v).slice(0,20))o[k]=shape(v[k],depth+1);return o;}if(typeof v==='string')return {type:'string',length:v.length,url_like:/^https?:\/\//.test(v)};return typeof v;}
const report={generated_at:new Date().toISOString(),catalogue:null,candidates:[],attempts:[],working_playback:null};
const cat=await req('/cms/web/hitv/movieDrama/moviePage');report.catalogue={http:cat.http,code:cat.code};const uniq=new Map();for(const i of collectItems(cat.data))if(!uniq.has(i.id))uniq.set(i.id,i);const candidates=[...uniq.values()].slice(0,8);report.candidates=candidates.map(x=>({id:x.id,category:x.category,name_present:Boolean(x.name)}));
for(const item of candidates){const params={id:item.id,category:item.category,seriesNo:1};const detail=await req('/cms/web/hitv/movieDrama/detail',{id:item.id,category:item.category});const play=await req('/cms/web/hitv/movieDrama/getPlayInfo',params);const download=await req('/cms/web/pc/download/urls',params);const preview=await req('/cms/web/pc/movieDrama/previewInfo',params,'POST');const result={id:item.id,category:item.category,detail:{http:detail.http,code:detail.code,message:detail.message},play:{http:play.http,code:play.code,message:play.message,media_count:mediaCount(play.data),shape:shape(play.data)},download:{http:download.http,code:download.code,message:download.message,media_count:mediaCount(download.data),shape:shape(download.data)},preview:{http:preview.http,code:preview.code,message:preview.message,media_count:mediaCount(preview.data),shape:shape(preview.data)}};report.attempts.push(result);if(result.play.media_count>0||result.download.media_count>0){report.working_playback=result;break;}}
fs.mkdirSync('diagnostics',{recursive:true});fs.writeFileSync('diagnostics/hitv-playback-probe.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
