#!/usr/bin/env node
import crypto from 'node:crypto';
import fs from 'node:fs';

const BASES=[
  'https://mobile-api.hitv.ltd',
  'https://mobile-api.hitv.space',
  'https://web-api.hitvpro.com',
];
const PUBLIC_KEY_DER='MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCEZTSwZTZdBfQAm8oVroRdy6K7VVB0/7Jojx7e3UPa7NjjZ2A/mydH7QI9aHr3dNEJDrNLyZ/nEK6XzV+XTG3t3GVqsEjVOVO26K/VcDVwk/dFJs8bmK3AaIBPQATJQDztgSjg5H7u92JnyXvtj0XB0IH+GM2ui6sB69Y5T0LPAwIDAQAB';
const PUBLIC_KEY=`-----BEGIN PUBLIC KEY-----\n${PUBLIC_KEY_DER.match(/.{1,64}/g).join('\n')}\n-----END PUBLIC KEY-----`;
function flatten(params,nested=false){const values=[];for(const key of Object.keys(params)){const value=params[key];if(value==null)continue;if(Array.isArray(value)){value.forEach((entry,index)=>{if(entry&&typeof entry==='object')values.push(`${key}=${flatten(entry,true)}`);else values.push(`${key}[${index}]=${String(entry)}`);});}else if(typeof value==='object')values.push(`${key}=${flatten(value,true)}`);else values.push(`${key}=${String(value)}`);}if(nested)values.sort((a,b)=>a<b?1:a>b?-1:0);return Buffer.from(values.map(v=>v.slice(v.indexOf('=')+1)).join(''),'utf8').toString('base64');}
function headers(params,uuid){const currentTime=Date.now().toString();const payload=`${currentTime}${flatten(params,true)}`.replaceAll('+','-').replaceAll('/','_');const cipher=crypto.createCipheriv('aes-128-ecb',Buffer.from(uuid),null);const encrypted=Buffer.concat([cipher.update(payload,'utf8'),cipher.final()]).toString('base64');return {'Content-Type':'application/json','Accept':'application/json','lang':'ar','currentTime,':undefined,currentTime,sign:crypto.createHash('md5').update(encrypted).digest('hex'),aesKey:crypto.publicEncrypt({key:PUBLIC_KEY,padding:crypto.constants.RSA_PKCS1_PADDING},Buffer.from(uuid)).toString('base64'),'User-Agent':'Mozilla/5.0 (Linux; Android 15) AppleWebKit/537.36 Chrome/127.0 Mobile Safari/537.36'};}
async function probe(base){const params={sequence:0,type:0};const uuid=crypto.randomBytes(8).toString('hex');const url=new URL('/cms/web/hitv/homePage/album/page',base);Object.entries(params).forEach(([k,v])=>url.searchParams.set(k,String(v)));const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),12000);const started=Date.now();try{const h=headers(params,uuid);delete h['currentTime,'];const r=await fetch(url,{headers:h,redirect:'follow',signal:controller.signal});const text=await r.text();let code=null,encrypted=false,itemHints=0;try{const j=JSON.parse(text);code=String(j.code??'');encrypted=typeof j.data==='string';if(Array.isArray(j.data))itemHints=j.data.length;}catch{}return {base,http:r.status,ok:r.ok,code,encrypted_data:encrypted,response_bytes:Buffer.byteLength(text),elapsed_ms:Date.now()-started};}catch(e){return {base,http:null,ok:false,error:e?.cause?.code||e?.name||'network',elapsed_ms:Date.now()-started};}finally{clearTimeout(timer);}}
const report={generated_at:new Date().toISOString(),probes:[]};for(const base of BASES)report.probes.push(await probe(base));fs.mkdirSync('diagnostics',{recursive:true});fs.writeFileSync('diagnostics/hitv-host-probe.json',JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));
